// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 요청 메시지
type CollectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectRequest) Reset() {
	*x = CollectRequest{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectRequest) ProtoMessage() {}

func (x *CollectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectRequest.ProtoReflect.Descriptor instead.
func (*CollectRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *CollectRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventTypes    []string               `protobuf:"bytes,1,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"` // ["interface", "neighbor"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *WatchRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

// 응답 메시지
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// 이벤트 메시지
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "interface", "neighbor"
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // JSON 형식의 이벤트 데이터
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Interface 관련 메시지
type InterfaceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interfaces    []*Interface           `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceList) Reset() {
	*x = InterfaceList{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceList) ProtoMessage() {}

func (x *InterfaceList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceList.ProtoReflect.Descriptor instead.
func (*InterfaceList) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *InterfaceList) GetInterfaces() []*Interface {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type Interface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SwIfIndex     uint32                 `protobuf:"varint,1,opt,name=sw_if_index,json=swIfIndex,proto3" json:"sw_if_index,omitempty"`
	InterfaceName string                 `protobuf:"bytes,2,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	AdminUp       bool                   `protobuf:"varint,3,opt,name=admin_up,json=adminUp,proto3" json:"admin_up,omitempty"`
	LinkUp        bool                   `protobuf:"varint,4,opt,name=link_up,json=linkUp,proto3" json:"link_up,omitempty"`
	L3Up          uint32                 `protobuf:"varint,5,opt,name=l3_up,json=l3Up,proto3" json:"l3_up,omitempty"`
	Flags         uint32                 `protobuf:"varint,6,opt,name=flags,proto3" json:"flags,omitempty"`
	Tag           string                 `protobuf:"bytes,7,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interface) Reset() {
	*x = Interface{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interface) ProtoMessage() {}

func (x *Interface) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interface.ProtoReflect.Descriptor instead.
func (*Interface) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *Interface) GetSwIfIndex() uint32 {
	if x != nil {
		return x.SwIfIndex
	}
	return 0
}

func (x *Interface) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *Interface) GetAdminUp() bool {
	if x != nil {
		return x.AdminUp
	}
	return false
}

func (x *Interface) GetLinkUp() bool {
	if x != nil {
		return x.LinkUp
	}
	return false
}

func (x *Interface) GetL3Up() uint32 {
	if x != nil {
		return x.L3Up
	}
	return 0
}

func (x *Interface) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Interface) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

// Neighbor 관련 메시지
type NeighborList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Neighbors     []*Neighbor            `protobuf:"bytes,1,rep,name=neighbors,proto3" json:"neighbors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeighborList) Reset() {
	*x = NeighborList{}
	mi := &file_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeighborList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeighborList) ProtoMessage() {}

func (x *NeighborList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeighborList.ProtoReflect.Descriptor instead.
func (*NeighborList) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *NeighborList) GetNeighbors() []*Neighbor {
	if x != nil {
		return x.Neighbors
	}
	return nil
}

type Neighbor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpAddress     string                 `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	MacAddress    string                 `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	SwIfIndex     uint32                 `protobuf:"varint,3,opt,name=sw_if_index,json=swIfIndex,proto3" json:"sw_if_index,omitempty"`
	IsStatic      bool                   `protobuf:"varint,4,opt,name=is_static,json=isStatic,proto3" json:"is_static,omitempty"`
	IsIpv6        bool                   `protobuf:"varint,5,opt,name=is_ipv6,json=isIpv6,proto3" json:"is_ipv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Neighbor) Reset() {
	*x = Neighbor{}
	mi := &file_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Neighbor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Neighbor) ProtoMessage() {}

func (x *Neighbor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Neighbor.ProtoReflect.Descriptor instead.
func (*Neighbor) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *Neighbor) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Neighbor) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *Neighbor) GetSwIfIndex() uint32 {
	if x != nil {
		return x.SwIfIndex
	}
	return 0
}

func (x *Neighbor) GetIsStatic() bool {
	if x != nil {
		return x.IsStatic
	}
	return false
}

func (x *Neighbor) GetIsIpv6() bool {
	if x != nil {
		return x.IsIpv6
	}
	return false
}

// FIB 관련 메시지
type FIBList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*FIBEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FIBList) Reset() {
	*x = FIBList{}
	mi := &file_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FIBList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FIBList) ProtoMessage() {}

func (x *FIBList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FIBList.ProtoReflect.Descriptor instead.
func (*FIBList) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *FIBList) GetEntries() []*FIBEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type FIBEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	SwIfIndex     uint32                 `protobuf:"varint,2,opt,name=sw_if_index,json=swIfIndex,proto3" json:"sw_if_index,omitempty"`
	NextHop       string                 `protobuf:"bytes,3,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
	Weight        uint32                 `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	Preference    uint32                 `protobuf:"varint,5,opt,name=preference,proto3" json:"preference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FIBEntry) Reset() {
	*x = FIBEntry{}
	mi := &file_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FIBEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FIBEntry) ProtoMessage() {}

func (x *FIBEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FIBEntry.ProtoReflect.Descriptor instead.
func (*FIBEntry) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *FIBEntry) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *FIBEntry) GetSwIfIndex() uint32 {
	if x != nil {
		return x.SwIfIndex
	}
	return 0
}

func (x *FIBEntry) GetNextHop() string {
	if x != nil {
		return x.NextHop
	}
	return ""
}

func (x *FIBEntry) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *FIBEntry) GetPreference() uint32 {
	if x != nil {
		return x.Preference
	}
	return 0
}

// ACL 관련 메시지
type ACLList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ACLEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACLList) Reset() {
	*x = ACLList{}
	mi := &file_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACLList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACLList) ProtoMessage() {}

func (x *ACLList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACLList.ProtoReflect.Descriptor instead.
func (*ACLList) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ACLList) GetEntries() []*ACLEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ACLEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AclIndex      uint32                 `protobuf:"varint,1,opt,name=acl_index,json=aclIndex,proto3" json:"acl_index,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACLEntry) Reset() {
	*x = ACLEntry{}
	mi := &file_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACLEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACLEntry) ProtoMessage() {}

func (x *ACLEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACLEntry.ProtoReflect.Descriptor instead.
func (*ACLEntry) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ACLEntry) GetAclIndex() uint32 {
	if x != nil {
		return x.AclIndex
	}
	return 0
}

func (x *ACLEntry) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ACLEntry) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Memif 관련 메시지
type MemifList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*MemifEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemifList) Reset() {
	*x = MemifList{}
	mi := &file_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemifList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemifList) ProtoMessage() {}

func (x *MemifList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemifList.ProtoReflect.Descriptor instead.
func (*MemifList) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *MemifList) GetEntries() []*MemifEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type MemifEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SwIfIndex      uint32                 `protobuf:"varint,1,opt,name=sw_if_index,json=swIfIndex,proto3" json:"sw_if_index,omitempty"`
	SocketFilename string                 `protobuf:"bytes,2,opt,name=socket_filename,json=socketFilename,proto3" json:"socket_filename,omitempty"`
	Id             uint32                 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Role           bool                   `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"`
	Mode           uint32                 `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`
	RingSize       uint32                 `protobuf:"varint,6,opt,name=ring_size,json=ringSize,proto3" json:"ring_size,omitempty"`
	BufferSize     uint32                 `protobuf:"varint,7,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MemifEntry) Reset() {
	*x = MemifEntry{}
	mi := &file_proto_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemifEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemifEntry) ProtoMessage() {}

func (x *MemifEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemifEntry.ProtoReflect.Descriptor instead.
func (*MemifEntry) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{14}
}

func (x *MemifEntry) GetSwIfIndex() uint32 {
	if x != nil {
		return x.SwIfIndex
	}
	return 0
}

func (x *MemifEntry) GetSocketFilename() string {
	if x != nil {
		return x.SocketFilename
	}
	return ""
}

func (x *MemifEntry) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MemifEntry) GetRole() bool {
	if x != nil {
		return x.Role
	}
	return false
}

func (x *MemifEntry) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *MemifEntry) GetRingSize() uint32 {
	if x != nil {
		return x.RingSize
	}
	return 0
}

func (x *MemifEntry) GetBufferSize() uint32 {
	if x != nil {
		return x.BufferSize
	}
	return 0
}

// SRv6 관련 메시지
type SRv6List struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*SRv6Entry           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SRv6List) Reset() {
	*x = SRv6List{}
	mi := &file_proto_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SRv6List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRv6List) ProtoMessage() {}

func (x *SRv6List) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRv6List.ProtoReflect.Descriptor instead.
func (*SRv6List) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{15}
}

func (x *SRv6List) GetEntries() []*SRv6Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type SRv6Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           string                 `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Behavior      uint32                 `protobuf:"varint,2,opt,name=behavior,proto3" json:"behavior,omitempty"`
	SwIfIndex     uint32                 `protobuf:"varint,3,opt,name=sw_if_index,json=swIfIndex,proto3" json:"sw_if_index,omitempty"`
	FibTable      uint32                 `protobuf:"varint,4,opt,name=fib_table,json=fibTable,proto3" json:"fib_table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SRv6Entry) Reset() {
	*x = SRv6Entry{}
	mi := &file_proto_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SRv6Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRv6Entry) ProtoMessage() {}

func (x *SRv6Entry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRv6Entry.ProtoReflect.Descriptor instead.
func (*SRv6Entry) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{16}
}

func (x *SRv6Entry) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *SRv6Entry) GetBehavior() uint32 {
	if x != nil {
		return x.Behavior
	}
	return 0
}

func (x *SRv6Entry) GetSwIfIndex() uint32 {
	if x != nil {
		return x.SwIfIndex
	}
	return 0
}

func (x *SRv6Entry) GetFibTable() uint32 {
	if x != nil {
		return x.FibTable
	}
	return 0
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\ttnc.agent\",\n" +
	"\x0eCollectRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\"/\n" +
	"\fWatchRequest\x12\x1f\n" +
	"\vevent_types\x18\x01 \x03(\tR\n" +
	"eventTypes\"\x14\n" +
	"\x12HealthCheckRequest\"e\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"M\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"E\n" +
	"\rInterfaceList\x124\n" +
	"\n" +
	"interfaces\x18\x01 \x03(\v2\x14.tnc.agent.InterfaceR\n" +
	"interfaces\"\xc3\x01\n" +
	"\tInterface\x12\x1e\n" +
	"\vsw_if_index\x18\x01 \x01(\rR\tswIfIndex\x12%\n" +
	"\x0einterface_name\x18\x02 \x01(\tR\rinterfaceName\x12\x19\n" +
	"\badmin_up\x18\x03 \x01(\bR\aadminUp\x12\x17\n" +
	"\alink_up\x18\x04 \x01(\bR\x06linkUp\x12\x13\n" +
	"\x05l3_up\x18\x05 \x01(\rR\x04l3Up\x12\x14\n" +
	"\x05flags\x18\x06 \x01(\rR\x05flags\x12\x10\n" +
	"\x03tag\x18\a \x01(\tR\x03tag\"A\n" +
	"\fNeighborList\x121\n" +
	"\tneighbors\x18\x01 \x03(\v2\x13.tnc.agent.NeighborR\tneighbors\"\xa0\x01\n" +
	"\bNeighbor\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\x12\x1f\n" +
	"\vmac_address\x18\x02 \x01(\tR\n" +
	"macAddress\x12\x1e\n" +
	"\vsw_if_index\x18\x03 \x01(\rR\tswIfIndex\x12\x1b\n" +
	"\tis_static\x18\x04 \x01(\bR\bisStatic\x12\x17\n" +
	"\ais_ipv6\x18\x05 \x01(\bR\x06isIpv6\"8\n" +
	"\aFIBList\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.tnc.agent.FIBEntryR\aentries\"\x95\x01\n" +
	"\bFIBEntry\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x1e\n" +
	"\vsw_if_index\x18\x02 \x01(\rR\tswIfIndex\x12\x19\n" +
	"\bnext_hop\x18\x03 \x01(\tR\anextHop\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\rR\x06weight\x12\x1e\n" +
	"\n" +
	"preference\x18\x05 \x01(\rR\n" +
	"preference\"8\n" +
	"\aACLList\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.tnc.agent.ACLEntryR\aentries\"O\n" +
	"\bACLEntry\x12\x1b\n" +
	"\tacl_index\x18\x01 \x01(\rR\baclIndex\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\"<\n" +
	"\tMemifList\x12/\n" +
	"\aentries\x18\x01 \x03(\v2\x15.tnc.agent.MemifEntryR\aentries\"\xcb\x01\n" +
	"\n" +
	"MemifEntry\x12\x1e\n" +
	"\vsw_if_index\x18\x01 \x01(\rR\tswIfIndex\x12'\n" +
	"\x0fsocket_filename\x18\x02 \x01(\tR\x0esocketFilename\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\rR\x02id\x12\x12\n" +
	"\x04role\x18\x04 \x01(\bR\x04role\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\rR\x04mode\x12\x1b\n" +
	"\tring_size\x18\x06 \x01(\rR\bringSize\x12\x1f\n" +
	"\vbuffer_size\x18\a \x01(\rR\n" +
	"bufferSize\":\n" +
	"\bSRv6List\x12.\n" +
	"\aentries\x18\x01 \x03(\v2\x14.tnc.agent.SRv6EntryR\aentries\"v\n" +
	"\tSRv6Entry\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\tR\x03sid\x12\x1a\n" +
	"\bbehavior\x18\x02 \x01(\rR\bbehavior\x12\x1e\n" +
	"\vsw_if_index\x18\x03 \x01(\rR\tswIfIndex\x12\x1b\n" +
	"\tfib_table\x18\x04 \x01(\rR\bfibTable2\xa0\x04\n" +
	"\bTncAgent\x12H\n" +
	"\x11CollectInterfaces\x12\x19.tnc.agent.CollectRequest\x1a\x18.tnc.agent.InterfaceList\x12F\n" +
	"\x10CollectNeighbors\x12\x19.tnc.agent.CollectRequest\x1a\x17.tnc.agent.NeighborList\x12;\n" +
	"\n" +
	"CollectFIB\x12\x19.tnc.agent.CollectRequest\x1a\x12.tnc.agent.FIBList\x12;\n" +
	"\n" +
	"CollectACL\x12\x19.tnc.agent.CollectRequest\x1a\x12.tnc.agent.ACLList\x12?\n" +
	"\fCollectMemif\x12\x19.tnc.agent.CollectRequest\x1a\x14.tnc.agent.MemifList\x12=\n" +
	"\vCollectSRv6\x12\x19.tnc.agent.CollectRequest\x1a\x13.tnc.agent.SRv6List\x12L\n" +
	"\vHealthCheck\x12\x1d.tnc.agent.HealthCheckRequest\x1a\x1e.tnc.agent.HealthCheckResponse\x12:\n" +
	"\vWatchEvents\x12\x17.tnc.agent.WatchRequest\x1a\x10.tnc.agent.Event0\x01B\x14Z\x12esba-tnc-api/protob\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_agent_proto_goTypes = []any{
	(*CollectRequest)(nil),      // 0: tnc.agent.CollectRequest
	(*WatchRequest)(nil),        // 1: tnc.agent.WatchRequest
	(*HealthCheckRequest)(nil),  // 2: tnc.agent.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 3: tnc.agent.HealthCheckResponse
	(*Event)(nil),               // 4: tnc.agent.Event
	(*InterfaceList)(nil),       // 5: tnc.agent.InterfaceList
	(*Interface)(nil),           // 6: tnc.agent.Interface
	(*NeighborList)(nil),        // 7: tnc.agent.NeighborList
	(*Neighbor)(nil),            // 8: tnc.agent.Neighbor
	(*FIBList)(nil),             // 9: tnc.agent.FIBList
	(*FIBEntry)(nil),            // 10: tnc.agent.FIBEntry
	(*ACLList)(nil),             // 11: tnc.agent.ACLList
	(*ACLEntry)(nil),            // 12: tnc.agent.ACLEntry
	(*MemifList)(nil),           // 13: tnc.agent.MemifList
	(*MemifEntry)(nil),          // 14: tnc.agent.MemifEntry
	(*SRv6List)(nil),            // 15: tnc.agent.SRv6List
	(*SRv6Entry)(nil),           // 16: tnc.agent.SRv6Entry
}
var file_proto_agent_proto_depIdxs = []int32{
	6,  // 0: tnc.agent.InterfaceList.interfaces:type_name -> tnc.agent.Interface
	8,  // 1: tnc.agent.NeighborList.neighbors:type_name -> tnc.agent.Neighbor
	10, // 2: tnc.agent.FIBList.entries:type_name -> tnc.agent.FIBEntry
	12, // 3: tnc.agent.ACLList.entries:type_name -> tnc.agent.ACLEntry
	14, // 4: tnc.agent.MemifList.entries:type_name -> tnc.agent.MemifEntry
	16, // 5: tnc.agent.SRv6List.entries:type_name -> tnc.agent.SRv6Entry
	0,  // 6: tnc.agent.TncAgent.CollectInterfaces:input_type -> tnc.agent.CollectRequest
	0,  // 7: tnc.agent.TncAgent.CollectNeighbors:input_type -> tnc.agent.CollectRequest
	0,  // 8: tnc.agent.TncAgent.CollectFIB:input_type -> tnc.agent.CollectRequest
	0,  // 9: tnc.agent.TncAgent.CollectACL:input_type -> tnc.agent.CollectRequest
	0,  // 10: tnc.agent.TncAgent.CollectMemif:input_type -> tnc.agent.CollectRequest
	0,  // 11: tnc.agent.TncAgent.CollectSRv6:input_type -> tnc.agent.CollectRequest
	2,  // 12: tnc.agent.TncAgent.HealthCheck:input_type -> tnc.agent.HealthCheckRequest
	1,  // 13: tnc.agent.TncAgent.WatchEvents:input_type -> tnc.agent.WatchRequest
	5,  // 14: tnc.agent.TncAgent.CollectInterfaces:output_type -> tnc.agent.InterfaceList
	7,  // 15: tnc.agent.TncAgent.CollectNeighbors:output_type -> tnc.agent.NeighborList
	9,  // 16: tnc.agent.TncAgent.CollectFIB:output_type -> tnc.agent.FIBList
	11, // 17: tnc.agent.TncAgent.CollectACL:output_type -> tnc.agent.ACLList
	13, // 18: tnc.agent.TncAgent.CollectMemif:output_type -> tnc.agent.MemifList
	15, // 19: tnc.agent.TncAgent.CollectSRv6:output_type -> tnc.agent.SRv6List
	3,  // 20: tnc.agent.TncAgent.HealthCheck:output_type -> tnc.agent.HealthCheckResponse
	4,  // 21: tnc.agent.TncAgent.WatchEvents:output_type -> tnc.agent.Event
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
