// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 요청 메시지
type CollectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectRequest) Reset() {
	*x = CollectRequest{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectRequest) ProtoMessage() {}

func (x *CollectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectRequest.ProtoReflect.Descriptor instead.
func (*CollectRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *CollectRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventTypes    []string               `protobuf:"bytes,1,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"` // ["interface", "neighbor"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *WatchRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

// 응답 메시지
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// 이벤트 메시지
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "interface", "neighbor"
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // JSON 형식의 이벤트 데이터
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Interface 관련 메시지
type InterfaceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interfaces    []*Interface           `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceList) Reset() {
	*x = InterfaceList{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceList) ProtoMessage() {}

func (x *InterfaceList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceList.ProtoReflect.Descriptor instead.
func (*InterfaceList) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *InterfaceList) GetInterfaces() []*Interface {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type Interface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SwIfIndex     uint32                 `protobuf:"varint,1,opt,name=sw_if_index,json=swIfIndex,proto3" json:"sw_if_index,omitempty"`
	InterfaceName string                 `protobuf:"bytes,2,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	AdminUp       bool                   `protobuf:"varint,3,opt,name=admin_up,json=adminUp,proto3" json:"admin_up,omitempty"`
	LinkUp        bool                   `protobuf:"varint,4,opt,name=link_up,json=linkUp,proto3" json:"link_up,omitempty"`
	L3Up          uint32                 `protobuf:"varint,5,opt,name=l3_up,json=l3Up,proto3" json:"l3_up,omitempty"`
	Flags         uint32                 `protobuf:"varint,6,opt,name=flags,proto3" json:"flags,omitempty"`
	Tag           string                 `protobuf:"bytes,7,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interface) Reset() {
	*x = Interface{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interface) ProtoMessage() {}

func (x *Interface) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interface.ProtoReflect.Descriptor instead.
func (*Interface) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *Interface) GetSwIfIndex() uint32 {
	if x != nil {
		return x.SwIfIndex
	}
	return 0
}

func (x *Interface) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *Interface) GetAdminUp() bool {
	if x != nil {
		return x.AdminUp
	}
	return false
}

func (x *Interface) GetLinkUp() bool {
	if x != nil {
		return x.LinkUp
	}
	return false
}

func (x *Interface) GetL3Up() uint32 {
	if x != nil {
		return x.L3Up
	}
	return 0
}

func (x *Interface) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Interface) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

// Neighbor 관련 메시지
type NeighborList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Neighbors     []*Neighbor            `protobuf:"bytes,1,rep,name=neighbors,proto3" json:"neighbors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeighborList) Reset() {
	*x = NeighborList{}
	mi := &file_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeighborList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeighborList) ProtoMessage() {}

func (x *NeighborList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeighborList.ProtoReflect.Descriptor instead.
func (*NeighborList) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *NeighborList) GetNeighbors() []*Neighbor {
	if x != nil {
		return x.Neighbors
	}
	return nil
}

type Neighbor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpAddress     string                 `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	MacAddress    string                 `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	SwIfIndex     uint32                 `protobuf:"varint,3,opt,name=sw_if_index,json=swIfIndex,proto3" json:"sw_if_index,omitempty"`
	IsStatic      bool                   `protobuf:"varint,4,opt,name=is_static,json=isStatic,proto3" json:"is_static,omitempty"`
	IsIpv6        bool                   `protobuf:"varint,5,opt,name=is_ipv6,json=isIpv6,proto3" json:"is_ipv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Neighbor) Reset() {
	*x = Neighbor{}
	mi := &file_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Neighbor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Neighbor) ProtoMessage() {}

func (x *Neighbor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Neighbor.ProtoReflect.Descriptor instead.
func (*Neighbor) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *Neighbor) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Neighbor) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *Neighbor) GetSwIfIndex() uint32 {
	if x != nil {
		return x.SwIfIndex
	}
	return 0
}

func (x *Neighbor) GetIsStatic() bool {
	if x != nil {
		return x.IsStatic
	}
	return false
}

func (x *Neighbor) GetIsIpv6() bool {
	if x != nil {
		return x.IsIpv6
	}
	return false
}

// FIB 관련 메시지
type FIBList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*FIBEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FIBList) Reset() {
	*x = FIBList{}
	mi := &file_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FIBList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FIBList) ProtoMessage() {}

func (x *FIBList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FIBList.ProtoReflect.Descriptor instead.
func (*FIBList) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *FIBList) GetEntries() []*FIBEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type FIBEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	SwIfIndex     uint32                 `protobuf:"varint,2,opt,name=sw_if_index,json=swIfIndex,proto3" json:"sw_if_index,omitempty"`
	NextHop       string                 `protobuf:"bytes,3,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
	Weight        uint32                 `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	Preference    uint32                 `protobuf:"varint,5,opt,name=preference,proto3" json:"preference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FIBEntry) Reset() {
	*x = FIBEntry{}
	mi := &file_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FIBEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FIBEntry) ProtoMessage() {}

func (x *FIBEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FIBEntry.ProtoReflect.Descriptor instead.
func (*FIBEntry) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *FIBEntry) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *FIBEntry) GetSwIfIndex() uint32 {
	if x != nil {
		return x.SwIfIndex
	}
	return 0
}

func (x *FIBEntry) GetNextHop() string {
	if x != nil {
		return x.NextHop
	}
	return ""
}

func (x *FIBEntry) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *FIBEntry) GetPreference() uint32 {
	if x != nil {
		return x.Preference
	}
	return 0
}

// ACL 관련 메시지
type ACLList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ACLEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACLList) Reset() {
	*x = ACLList{}
	mi := &file_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACLList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACLList) ProtoMessage() {}

func (x *ACLList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACLList.ProtoReflect.Descriptor instead.
func (*ACLList) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ACLList) GetEntries() []*ACLEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ACLEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AclIndex      uint32                 `protobuf:"varint,1,opt,name=acl_index,json=aclIndex,proto3" json:"acl_index,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACLEntry) Reset() {
	*x = ACLEntry{}
	mi := &file_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACLEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACLEntry) ProtoMessage() {}

func (x *ACLEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACLEntry.ProtoReflect.Descriptor instead.
func (*ACLEntry) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ACLEntry) GetAclIndex() uint32 {
	if x != nil {
		return x.AclIndex
	}
	return 0
}

func (x *ACLEntry) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ACLEntry) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Memif 관련 메시지
type MemifList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*MemifEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemifList) Reset() {
	*x = MemifList{}
	mi := &file_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemifList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemifList) ProtoMessage() {}

func (x *MemifList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemifList.ProtoReflect.Descriptor instead.
func (*MemifList) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *MemifList) GetEntries() []*MemifEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type MemifEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SwIfIndex      uint32                 `protobuf:"varint,1,opt,name=sw_if_index,json=swIfIndex,proto3" json:"sw_if_index,omitempty"`
	SocketFilename string                 `protobuf:"bytes,2,opt,name=socket_filename,json=socketFilename,proto3" json:"socket_filename,omitempty"`
	Id             uint32                 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Role           bool                   `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"`
	Mode           uint32                 `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`
	RingSize       uint32                 `protobuf:"varint,6,opt,name=ring_size,json=ringSize,proto3" json:"ring_size,omitempty"`
	BufferSize     uint32                 `protobuf:"varint,7,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MemifEntry) Reset() {
	*x = MemifEntry{}
	mi := &file_proto_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemifEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemifEntry) ProtoMessage() {}

func (x *MemifEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemifEntry.ProtoReflect.Descriptor instead.
func (*MemifEntry) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{14}
}

func (x *MemifEntry) GetSwIfIndex() uint32 {
	if x != nil {
		return x.SwIfIndex
	}
	return 0
}

func (x *MemifEntry) GetSocketFilename() string {
	if x != nil {
		return x.SocketFilename
	}
	return ""
}

func (x *MemifEntry) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MemifEntry) GetRole() bool {
	if x != nil {
		return x.Role
	}
	return false
}

func (x *MemifEntry) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *MemifEntry) GetRingSize() uint32 {
	if x != nil {
		return x.RingSize
	}
	return 0
}

func (x *MemifEntry) GetBufferSize() uint32 {
	if x != nil {
		return x.BufferSize
	}
	return 0
}

// SRv6 관련 메시지
type SRv6List struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*SRv6Entry           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SRv6List) Reset() {
	*x = SRv6List{}
	mi := &file_proto_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SRv6List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRv6List) ProtoMessage() {}

func (x *SRv6List) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRv6List.ProtoReflect.Descriptor instead.
func (*SRv6List) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{15}
}

func (x *SRv6List) GetEntries() []*SRv6Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type SRv6Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           string                 `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Behavior      uint32                 `protobuf:"varint,2,opt,name=behavior,proto3" json:"behavior,omitempty"`
	SwIfIndex     uint32                 `protobuf:"varint,3,opt,name=sw_if_index,json=swIfIndex,proto3" json:"sw_if_index,omitempty"`
	FibTable      uint32                 `protobuf:"varint,4,opt,name=fib_table,json=fibTable,proto3" json:"fib_table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SRv6Entry) Reset() {
	*x = SRv6Entry{}
	mi := &file_proto_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SRv6Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRv6Entry) ProtoMessage() {}

func (x *SRv6Entry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRv6Entry.ProtoReflect.Descriptor instead.
func (*SRv6Entry) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{16}
}

func (x *SRv6Entry) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *SRv6Entry) GetBehavior() uint32 {
	if x != nil {
		return x.Behavior
	}
	return 0
}

func (x *SRv6Entry) GetSwIfIndex() uint32 {
	if x != nil {
		return x.SwIfIndex
	}
	return 0
}

func (x *SRv6Entry) GetFibTable() uint32 {
	if x != nil {
		return x.FibTable
	}
	return 0
}

// Version 관련 메시지
type VersionInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Program        string                 `protobuf:"bytes,1,opt,name=program,proto3" json:"program,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	BuildDate      string                 `protobuf:"bytes,3,opt,name=build_date,json=buildDate,proto3" json:"build_date,omitempty"`
	BuildDirectory string                 `protobuf:"bytes,4,opt,name=build_directory,json=buildDirectory,proto3" json:"build_directory,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VersionInfo) Reset() {
	*x = VersionInfo{}
	mi := &file_proto_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionInfo) ProtoMessage() {}

func (x *VersionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionInfo.ProtoReflect.Descriptor instead.
func (*VersionInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{17}
}

func (x *VersionInfo) GetProgram() string {
	if x != nil {
		return x.Program
	}
	return ""
}

func (x *VersionInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VersionInfo) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

func (x *VersionInfo) GetBuildDirectory() string {
	if x != nil {
		return x.BuildDirectory
	}
	return ""
}

// Hardware 관련 메시지
type HardwareInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          string                 `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"` // CLI 출력 결과 (문자열)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HardwareInfo) Reset() {
	*x = HardwareInfo{}
	mi := &file_proto_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareInfo) ProtoMessage() {}

func (x *HardwareInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareInfo.ProtoReflect.Descriptor instead.
func (*HardwareInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{18}
}

func (x *HardwareInfo) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

// IP Address 관련 메시지
type IPAddressList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*IPAddressEntry      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPAddressList) Reset() {
	*x = IPAddressList{}
	mi := &file_proto_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPAddressList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPAddressList) ProtoMessage() {}

func (x *IPAddressList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPAddressList.ProtoReflect.Descriptor instead.
func (*IPAddressList) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{19}
}

func (x *IPAddressList) GetEntries() []*IPAddressEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type IPAddressEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"` // 예: "192.168.1.1/24"
	SwIfIndex     uint32                 `protobuf:"varint,2,opt,name=sw_if_index,json=swIfIndex,proto3" json:"sw_if_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPAddressEntry) Reset() {
	*x = IPAddressEntry{}
	mi := &file_proto_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPAddressEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPAddressEntry) ProtoMessage() {}

func (x *IPAddressEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPAddressEntry.ProtoReflect.Descriptor instead.
func (*IPAddressEntry) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{20}
}

func (x *IPAddressEntry) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *IPAddressEntry) GetSwIfIndex() uint32 {
	if x != nil {
		return x.SwIfIndex
	}
	return 0
}

// L2 FIB 관련 메시지
type L2FIBList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*L2FIBEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L2FIBList) Reset() {
	*x = L2FIBList{}
	mi := &file_proto_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L2FIBList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2FIBList) ProtoMessage() {}

func (x *L2FIBList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2FIBList.ProtoReflect.Descriptor instead.
func (*L2FIBList) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{21}
}

func (x *L2FIBList) GetEntries() []*L2FIBEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type L2FIBEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BdId          uint32                 `protobuf:"varint,1,opt,name=bd_id,json=bdId,proto3" json:"bd_id,omitempty"`
	Mac           string                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"` // MAC 주소 문자열
	SwIfIndex     uint32                 `protobuf:"varint,3,opt,name=sw_if_index,json=swIfIndex,proto3" json:"sw_if_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L2FIBEntry) Reset() {
	*x = L2FIBEntry{}
	mi := &file_proto_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L2FIBEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2FIBEntry) ProtoMessage() {}

func (x *L2FIBEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2FIBEntry.ProtoReflect.Descriptor instead.
func (*L2FIBEntry) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{22}
}

func (x *L2FIBEntry) GetBdId() uint32 {
	if x != nil {
		return x.BdId
	}
	return 0
}

func (x *L2FIBEntry) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *L2FIBEntry) GetSwIfIndex() uint32 {
	if x != nil {
		return x.SwIfIndex
	}
	return 0
}

// Bridge Domain 관련 메시지
type BridgeDomainList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*BridgeDomainEntry   `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BridgeDomainList) Reset() {
	*x = BridgeDomainList{}
	mi := &file_proto_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeDomainList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeDomainList) ProtoMessage() {}

func (x *BridgeDomainList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeDomainList.ProtoReflect.Descriptor instead.
func (*BridgeDomainList) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{23}
}

func (x *BridgeDomainList) GetEntries() []*BridgeDomainEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type BridgeDomainEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BdId          uint32                 `protobuf:"varint,1,opt,name=bd_id,json=bdId,proto3" json:"bd_id,omitempty"`
	Flags         []string               `protobuf:"bytes,2,rep,name=flags,proto3" json:"flags,omitempty"`                    // ["flood", "forward", "learn", ...]
	NSwIfs        uint32                 `protobuf:"varint,3,opt,name=n_sw_ifs,json=nSwIfs,proto3" json:"n_sw_ifs,omitempty"` // 연결된 인터페이스 수
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BridgeDomainEntry) Reset() {
	*x = BridgeDomainEntry{}
	mi := &file_proto_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeDomainEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeDomainEntry) ProtoMessage() {}

func (x *BridgeDomainEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeDomainEntry.ProtoReflect.Descriptor instead.
func (*BridgeDomainEntry) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{24}
}

func (x *BridgeDomainEntry) GetBdId() uint32 {
	if x != nil {
		return x.BdId
	}
	return 0
}

func (x *BridgeDomainEntry) GetFlags() []string {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *BridgeDomainEntry) GetNSwIfs() uint32 {
	if x != nil {
		return x.NSwIfs
	}
	return 0
}

// VXLAN 관련 메시지
type VXLANList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*VXLANEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VXLANList) Reset() {
	*x = VXLANList{}
	mi := &file_proto_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VXLANList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VXLANList) ProtoMessage() {}

func (x *VXLANList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VXLANList.ProtoReflect.Descriptor instead.
func (*VXLANList) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{25}
}

func (x *VXLANList) GetEntries() []*VXLANEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type VXLANEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SwIfIndex     uint32                 `protobuf:"varint,1,opt,name=sw_if_index,json=swIfIndex,proto3" json:"sw_if_index,omitempty"`
	Src           string                 `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`  // 소스 IP 주소
	Dst           string                 `protobuf:"bytes,3,opt,name=dst,proto3" json:"dst,omitempty"`  // 목적지 IP 주소
	Vni           uint32                 `protobuf:"varint,4,opt,name=vni,proto3" json:"vni,omitempty"` // VXLAN Network Identifier
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VXLANEntry) Reset() {
	*x = VXLANEntry{}
	mi := &file_proto_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VXLANEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VXLANEntry) ProtoMessage() {}

func (x *VXLANEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VXLANEntry.ProtoReflect.Descriptor instead.
func (*VXLANEntry) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{26}
}

func (x *VXLANEntry) GetSwIfIndex() uint32 {
	if x != nil {
		return x.SwIfIndex
	}
	return 0
}

func (x *VXLANEntry) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *VXLANEntry) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *VXLANEntry) GetVni() uint32 {
	if x != nil {
		return x.Vni
	}
	return 0
}

// UPF 관련 메시지
type UPFApplicationList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applications  []*UPFApplication      `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UPFApplicationList) Reset() {
	*x = UPFApplicationList{}
	mi := &file_proto_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UPFApplicationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UPFApplicationList) ProtoMessage() {}

func (x *UPFApplicationList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UPFApplicationList.ProtoReflect.Descriptor instead.
func (*UPFApplicationList) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{27}
}

func (x *UPFApplicationList) GetApplications() []*UPFApplication {
	if x != nil {
		return x.Applications
	}
	return nil
}

type UPFApplication struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Flags         uint32                 `protobuf:"varint,2,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UPFApplication) Reset() {
	*x = UPFApplication{}
	mi := &file_proto_agent_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UPFApplication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UPFApplication) ProtoMessage() {}

func (x *UPFApplication) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UPFApplication.ProtoReflect.Descriptor instead.
func (*UPFApplication) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{28}
}

func (x *UPFApplication) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UPFApplication) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type UPFNWIList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nwis          []*UPFNWI              `protobuf:"bytes,1,rep,name=nwis,proto3" json:"nwis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UPFNWIList) Reset() {
	*x = UPFNWIList{}
	mi := &file_proto_agent_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UPFNWIList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UPFNWIList) ProtoMessage() {}

func (x *UPFNWIList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UPFNWIList.ProtoReflect.Descriptor instead.
func (*UPFNWIList) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{29}
}

func (x *UPFNWIList) GetNwis() []*UPFNWI {
	if x != nil {
		return x.Nwis
	}
	return nil
}

type UPFNWI struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Ip4TableId          uint32                 `protobuf:"varint,1,opt,name=ip4_table_id,json=ip4TableId,proto3" json:"ip4_table_id,omitempty"`
	Ip6TableId          uint32                 `protobuf:"varint,2,opt,name=ip6_table_id,json=ip6TableId,proto3" json:"ip6_table_id,omitempty"`
	IpfixCollectorIp    string                 `protobuf:"bytes,3,opt,name=ipfix_collector_ip,json=ipfixCollectorIp,proto3" json:"ipfix_collector_ip,omitempty"`
	IpfixReportInterval uint32                 `protobuf:"varint,4,opt,name=ipfix_report_interval,json=ipfixReportInterval,proto3" json:"ipfix_report_interval,omitempty"`
	ObservationDomainId uint32                 `protobuf:"varint,5,opt,name=observation_domain_id,json=observationDomainId,proto3" json:"observation_domain_id,omitempty"`
	ObservationPointId  uint64                 `protobuf:"varint,6,opt,name=observation_point_id,json=observationPointId,proto3" json:"observation_point_id,omitempty"`
	Nwi                 string                 `protobuf:"bytes,7,opt,name=nwi,proto3" json:"nwi,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UPFNWI) Reset() {
	*x = UPFNWI{}
	mi := &file_proto_agent_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UPFNWI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UPFNWI) ProtoMessage() {}

func (x *UPFNWI) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UPFNWI.ProtoReflect.Descriptor instead.
func (*UPFNWI) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{30}
}

func (x *UPFNWI) GetIp4TableId() uint32 {
	if x != nil {
		return x.Ip4TableId
	}
	return 0
}

func (x *UPFNWI) GetIp6TableId() uint32 {
	if x != nil {
		return x.Ip6TableId
	}
	return 0
}

func (x *UPFNWI) GetIpfixCollectorIp() string {
	if x != nil {
		return x.IpfixCollectorIp
	}
	return ""
}

func (x *UPFNWI) GetIpfixReportInterval() uint32 {
	if x != nil {
		return x.IpfixReportInterval
	}
	return 0
}

func (x *UPFNWI) GetObservationDomainId() uint32 {
	if x != nil {
		return x.ObservationDomainId
	}
	return 0
}

func (x *UPFNWI) GetObservationPointId() uint64 {
	if x != nil {
		return x.ObservationPointId
	}
	return 0
}

func (x *UPFNWI) GetNwi() string {
	if x != nil {
		return x.Nwi
	}
	return ""
}

type UPFPFCPEndpointList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []*UPFPFCPEndpoint     `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UPFPFCPEndpointList) Reset() {
	*x = UPFPFCPEndpointList{}
	mi := &file_proto_agent_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UPFPFCPEndpointList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UPFPFCPEndpointList) ProtoMessage() {}

func (x *UPFPFCPEndpointList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UPFPFCPEndpointList.ProtoReflect.Descriptor instead.
func (*UPFPFCPEndpointList) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{31}
}

func (x *UPFPFCPEndpointList) GetEndpoints() []*UPFPFCPEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type UPFPFCPEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableId       uint32                 `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UPFPFCPEndpoint) Reset() {
	*x = UPFPFCPEndpoint{}
	mi := &file_proto_agent_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UPFPFCPEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UPFPFCPEndpoint) ProtoMessage() {}

func (x *UPFPFCPEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UPFPFCPEndpoint.ProtoReflect.Descriptor instead.
func (*UPFPFCPEndpoint) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{32}
}

func (x *UPFPFCPEndpoint) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *UPFPFCPEndpoint) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type UPFPolicyList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []*UPFPolicy           `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UPFPolicyList) Reset() {
	*x = UPFPolicyList{}
	mi := &file_proto_agent_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UPFPolicyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UPFPolicyList) ProtoMessage() {}

func (x *UPFPolicyList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UPFPolicyList.ProtoReflect.Descriptor instead.
func (*UPFPolicyList) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{33}
}

func (x *UPFPolicyList) GetPolicies() []*UPFPolicy {
	if x != nil {
		return x.Policies
	}
	return nil
}

type UPFPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"` // paths는 복잡한 구조체 배열이므로 나중에 확장 가능
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UPFPolicy) Reset() {
	*x = UPFPolicy{}
	mi := &file_proto_agent_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UPFPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UPFPolicy) ProtoMessage() {}

func (x *UPFPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UPFPolicy.ProtoReflect.Descriptor instead.
func (*UPFPolicy) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{34}
}

func (x *UPFPolicy) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

type UPFNATPoolList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pools         []*UPFNATPool          `protobuf:"bytes,1,rep,name=pools,proto3" json:"pools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UPFNATPoolList) Reset() {
	*x = UPFNATPoolList{}
	mi := &file_proto_agent_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UPFNATPoolList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UPFNATPoolList) ProtoMessage() {}

func (x *UPFNATPoolList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UPFNATPoolList.ProtoReflect.Descriptor instead.
func (*UPFNATPoolList) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{35}
}

func (x *UPFNATPoolList) GetPools() []*UPFNATPool {
	if x != nil {
		return x.Pools
	}
	return nil
}

type UPFNATPool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BlockSize     uint32                 `protobuf:"varint,2,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	MaxUsers      uint32                 `protobuf:"varint,3,opt,name=max_users,json=maxUsers,proto3" json:"max_users,omitempty"`
	CurrentUsers  uint32                 `protobuf:"varint,4,opt,name=current_users,json=currentUsers,proto3" json:"current_users,omitempty"`
	Nwi           string                 `protobuf:"bytes,5,opt,name=nwi,proto3" json:"nwi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UPFNATPool) Reset() {
	*x = UPFNATPool{}
	mi := &file_proto_agent_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UPFNATPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UPFNATPool) ProtoMessage() {}

func (x *UPFNATPool) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UPFNATPool.ProtoReflect.Descriptor instead.
func (*UPFNATPool) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{36}
}

func (x *UPFNATPool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UPFNATPool) GetBlockSize() uint32 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *UPFNATPool) GetMaxUsers() uint32 {
	if x != nil {
		return x.MaxUsers
	}
	return 0
}

func (x *UPFNATPool) GetCurrentUsers() uint32 {
	if x != nil {
		return x.CurrentUsers
	}
	return 0
}

func (x *UPFNATPool) GetNwi() string {
	if x != nil {
		return x.Nwi
	}
	return ""
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\ttnc.agent\",\n" +
	"\x0eCollectRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\"/\n" +
	"\fWatchRequest\x12\x1f\n" +
	"\vevent_types\x18\x01 \x03(\tR\n" +
	"eventTypes\"\x14\n" +
	"\x12HealthCheckRequest\"e\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"M\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"E\n" +
	"\rInterfaceList\x124\n" +
	"\n" +
	"interfaces\x18\x01 \x03(\v2\x14.tnc.agent.InterfaceR\n" +
	"interfaces\"\xc3\x01\n" +
	"\tInterface\x12\x1e\n" +
	"\vsw_if_index\x18\x01 \x01(\rR\tswIfIndex\x12%\n" +
	"\x0einterface_name\x18\x02 \x01(\tR\rinterfaceName\x12\x19\n" +
	"\badmin_up\x18\x03 \x01(\bR\aadminUp\x12\x17\n" +
	"\alink_up\x18\x04 \x01(\bR\x06linkUp\x12\x13\n" +
	"\x05l3_up\x18\x05 \x01(\rR\x04l3Up\x12\x14\n" +
	"\x05flags\x18\x06 \x01(\rR\x05flags\x12\x10\n" +
	"\x03tag\x18\a \x01(\tR\x03tag\"A\n" +
	"\fNeighborList\x121\n" +
	"\tneighbors\x18\x01 \x03(\v2\x13.tnc.agent.NeighborR\tneighbors\"\xa0\x01\n" +
	"\bNeighbor\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\x12\x1f\n" +
	"\vmac_address\x18\x02 \x01(\tR\n" +
	"macAddress\x12\x1e\n" +
	"\vsw_if_index\x18\x03 \x01(\rR\tswIfIndex\x12\x1b\n" +
	"\tis_static\x18\x04 \x01(\bR\bisStatic\x12\x17\n" +
	"\ais_ipv6\x18\x05 \x01(\bR\x06isIpv6\"8\n" +
	"\aFIBList\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.tnc.agent.FIBEntryR\aentries\"\x95\x01\n" +
	"\bFIBEntry\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x1e\n" +
	"\vsw_if_index\x18\x02 \x01(\rR\tswIfIndex\x12\x19\n" +
	"\bnext_hop\x18\x03 \x01(\tR\anextHop\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\rR\x06weight\x12\x1e\n" +
	"\n" +
	"preference\x18\x05 \x01(\rR\n" +
	"preference\"8\n" +
	"\aACLList\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.tnc.agent.ACLEntryR\aentries\"O\n" +
	"\bACLEntry\x12\x1b\n" +
	"\tacl_index\x18\x01 \x01(\rR\baclIndex\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\"<\n" +
	"\tMemifList\x12/\n" +
	"\aentries\x18\x01 \x03(\v2\x15.tnc.agent.MemifEntryR\aentries\"\xcb\x01\n" +
	"\n" +
	"MemifEntry\x12\x1e\n" +
	"\vsw_if_index\x18\x01 \x01(\rR\tswIfIndex\x12'\n" +
	"\x0fsocket_filename\x18\x02 \x01(\tR\x0esocketFilename\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\rR\x02id\x12\x12\n" +
	"\x04role\x18\x04 \x01(\bR\x04role\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\rR\x04mode\x12\x1b\n" +
	"\tring_size\x18\x06 \x01(\rR\bringSize\x12\x1f\n" +
	"\vbuffer_size\x18\a \x01(\rR\n" +
	"bufferSize\":\n" +
	"\bSRv6List\x12.\n" +
	"\aentries\x18\x01 \x03(\v2\x14.tnc.agent.SRv6EntryR\aentries\"v\n" +
	"\tSRv6Entry\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\tR\x03sid\x12\x1a\n" +
	"\bbehavior\x18\x02 \x01(\rR\bbehavior\x12\x1e\n" +
	"\vsw_if_index\x18\x03 \x01(\rR\tswIfIndex\x12\x1b\n" +
	"\tfib_table\x18\x04 \x01(\rR\bfibTable\"\x89\x01\n" +
	"\vVersionInfo\x12\x18\n" +
	"\aprogram\x18\x01 \x01(\tR\aprogram\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"build_date\x18\x03 \x01(\tR\tbuildDate\x12'\n" +
	"\x0fbuild_directory\x18\x04 \x01(\tR\x0ebuildDirectory\"\"\n" +
	"\fHardwareInfo\x12\x12\n" +
	"\x04info\x18\x01 \x01(\tR\x04info\"D\n" +
	"\rIPAddressList\x123\n" +
	"\aentries\x18\x01 \x03(\v2\x19.tnc.agent.IPAddressEntryR\aentries\"H\n" +
	"\x0eIPAddressEntry\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x1e\n" +
	"\vsw_if_index\x18\x02 \x01(\rR\tswIfIndex\"<\n" +
	"\tL2FIBList\x12/\n" +
	"\aentries\x18\x01 \x03(\v2\x15.tnc.agent.L2FIBEntryR\aentries\"S\n" +
	"\n" +
	"L2FIBEntry\x12\x13\n" +
	"\x05bd_id\x18\x01 \x01(\rR\x04bdId\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\x12\x1e\n" +
	"\vsw_if_index\x18\x03 \x01(\rR\tswIfIndex\"J\n" +
	"\x10BridgeDomainList\x126\n" +
	"\aentries\x18\x01 \x03(\v2\x1c.tnc.agent.BridgeDomainEntryR\aentries\"X\n" +
	"\x11BridgeDomainEntry\x12\x13\n" +
	"\x05bd_id\x18\x01 \x01(\rR\x04bdId\x12\x14\n" +
	"\x05flags\x18\x02 \x03(\tR\x05flags\x12\x18\n" +
	"\bn_sw_ifs\x18\x03 \x01(\rR\x06nSwIfs\"<\n" +
	"\tVXLANList\x12/\n" +
	"\aentries\x18\x01 \x03(\v2\x15.tnc.agent.VXLANEntryR\aentries\"b\n" +
	"\n" +
	"VXLANEntry\x12\x1e\n" +
	"\vsw_if_index\x18\x01 \x01(\rR\tswIfIndex\x12\x10\n" +
	"\x03src\x18\x02 \x01(\tR\x03src\x12\x10\n" +
	"\x03dst\x18\x03 \x01(\tR\x03dst\x12\x10\n" +
	"\x03vni\x18\x04 \x01(\rR\x03vni\"S\n" +
	"\x12UPFApplicationList\x12=\n" +
	"\fapplications\x18\x01 \x03(\v2\x19.tnc.agent.UPFApplicationR\fapplications\":\n" +
	"\x0eUPFApplication\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05flags\x18\x02 \x01(\rR\x05flags\"3\n" +
	"\n" +
	"UPFNWIList\x12%\n" +
	"\x04nwis\x18\x01 \x03(\v2\x11.tnc.agent.UPFNWIR\x04nwis\"\xa6\x02\n" +
	"\x06UPFNWI\x12 \n" +
	"\fip4_table_id\x18\x01 \x01(\rR\n" +
	"ip4TableId\x12 \n" +
	"\fip6_table_id\x18\x02 \x01(\rR\n" +
	"ip6TableId\x12,\n" +
	"\x12ipfix_collector_ip\x18\x03 \x01(\tR\x10ipfixCollectorIp\x122\n" +
	"\x15ipfix_report_interval\x18\x04 \x01(\rR\x13ipfixReportInterval\x122\n" +
	"\x15observation_domain_id\x18\x05 \x01(\rR\x13observationDomainId\x120\n" +
	"\x14observation_point_id\x18\x06 \x01(\x04R\x12observationPointId\x12\x10\n" +
	"\x03nwi\x18\a \x01(\tR\x03nwi\"O\n" +
	"\x13UPFPFCPEndpointList\x128\n" +
	"\tendpoints\x18\x01 \x03(\v2\x1a.tnc.agent.UPFPFCPEndpointR\tendpoints\"<\n" +
	"\x0fUPFPFCPEndpoint\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\rR\atableId\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\"A\n" +
	"\rUPFPolicyList\x120\n" +
	"\bpolicies\x18\x01 \x03(\v2\x14.tnc.agent.UPFPolicyR\bpolicies\"+\n" +
	"\tUPFPolicy\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\"=\n" +
	"\x0eUPFNATPoolList\x12+\n" +
	"\x05pools\x18\x01 \x03(\v2\x15.tnc.agent.UPFNATPoolR\x05pools\"\x93\x01\n" +
	"\n" +
	"UPFNATPool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"block_size\x18\x02 \x01(\rR\tblockSize\x12\x1b\n" +
	"\tmax_users\x18\x03 \x01(\rR\bmaxUsers\x12#\n" +
	"\rcurrent_users\x18\x04 \x01(\rR\fcurrentUsers\x12\x10\n" +
	"\x03nwi\x18\x05 \x01(\tR\x03nwi2\xcd\n" +
	"\n" +
	"\bTncAgent\x12H\n" +
	"\x11CollectInterfaces\x12\x19.tnc.agent.CollectRequest\x1a\x18.tnc.agent.InterfaceList\x12F\n" +
	"\x10CollectNeighbors\x12\x19.tnc.agent.CollectRequest\x1a\x17.tnc.agent.NeighborList\x12;\n" +
	"\n" +
	"CollectFIB\x12\x19.tnc.agent.CollectRequest\x1a\x12.tnc.agent.FIBList\x12;\n" +
	"\n" +
	"CollectACL\x12\x19.tnc.agent.CollectRequest\x1a\x12.tnc.agent.ACLList\x12?\n" +
	"\fCollectMemif\x12\x19.tnc.agent.CollectRequest\x1a\x14.tnc.agent.MemifList\x12=\n" +
	"\vCollectSRv6\x12\x19.tnc.agent.CollectRequest\x1a\x13.tnc.agent.SRv6List\x12C\n" +
	"\x0eCollectVersion\x12\x19.tnc.agent.CollectRequest\x1a\x16.tnc.agent.VersionInfo\x12E\n" +
	"\x0fCollectHardware\x12\x19.tnc.agent.CollectRequest\x1a\x17.tnc.agent.HardwareInfo\x12I\n" +
	"\x12CollectIPAddresses\x12\x19.tnc.agent.CollectRequest\x1a\x18.tnc.agent.IPAddressList\x12?\n" +
	"\fCollectL2FIB\x12\x19.tnc.agent.CollectRequest\x1a\x14.tnc.agent.L2FIBList\x12N\n" +
	"\x14CollectBridgeDomains\x12\x19.tnc.agent.CollectRequest\x1a\x1b.tnc.agent.BridgeDomainList\x12?\n" +
	"\fCollectVXLAN\x12\x19.tnc.agent.CollectRequest\x1a\x14.tnc.agent.VXLANList\x12R\n" +
	"\x16CollectUPFApplications\x12\x19.tnc.agent.CollectRequest\x1a\x1d.tnc.agent.UPFApplicationList\x12A\n" +
	"\rCollectUPFNWI\x12\x19.tnc.agent.CollectRequest\x1a\x15.tnc.agent.UPFNWIList\x12T\n" +
	"\x17CollectUPFPFCPEndpoints\x12\x19.tnc.agent.CollectRequest\x1a\x1e.tnc.agent.UPFPFCPEndpointList\x12I\n" +
	"\x12CollectUPFPolicies\x12\x19.tnc.agent.CollectRequest\x1a\x18.tnc.agent.UPFPolicyList\x12J\n" +
	"\x12CollectUPFNATPools\x12\x19.tnc.agent.CollectRequest\x1a\x19.tnc.agent.UPFNATPoolList\x12L\n" +
	"\vHealthCheck\x12\x1d.tnc.agent.HealthCheckRequest\x1a\x1e.tnc.agent.HealthCheckResponse\x12:\n" +
	"\vWatchEvents\x12\x17.tnc.agent.WatchRequest\x1a\x10.tnc.agent.Event0\x01B\x14Z\x12esba-tnc-api/protob\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_proto_agent_proto_goTypes = []any{
	(*CollectRequest)(nil),      // 0: tnc.agent.CollectRequest
	(*WatchRequest)(nil),        // 1: tnc.agent.WatchRequest
	(*HealthCheckRequest)(nil),  // 2: tnc.agent.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 3: tnc.agent.HealthCheckResponse
	(*Event)(nil),               // 4: tnc.agent.Event
	(*InterfaceList)(nil),       // 5: tnc.agent.InterfaceList
	(*Interface)(nil),           // 6: tnc.agent.Interface
	(*NeighborList)(nil),        // 7: tnc.agent.NeighborList
	(*Neighbor)(nil),            // 8: tnc.agent.Neighbor
	(*FIBList)(nil),             // 9: tnc.agent.FIBList
	(*FIBEntry)(nil),            // 10: tnc.agent.FIBEntry
	(*ACLList)(nil),             // 11: tnc.agent.ACLList
	(*ACLEntry)(nil),            // 12: tnc.agent.ACLEntry
	(*MemifList)(nil),           // 13: tnc.agent.MemifList
	(*MemifEntry)(nil),          // 14: tnc.agent.MemifEntry
	(*SRv6List)(nil),            // 15: tnc.agent.SRv6List
	(*SRv6Entry)(nil),           // 16: tnc.agent.SRv6Entry
	(*VersionInfo)(nil),         // 17: tnc.agent.VersionInfo
	(*HardwareInfo)(nil),        // 18: tnc.agent.HardwareInfo
	(*IPAddressList)(nil),       // 19: tnc.agent.IPAddressList
	(*IPAddressEntry)(nil),      // 20: tnc.agent.IPAddressEntry
	(*L2FIBList)(nil),           // 21: tnc.agent.L2FIBList
	(*L2FIBEntry)(nil),          // 22: tnc.agent.L2FIBEntry
	(*BridgeDomainList)(nil),    // 23: tnc.agent.BridgeDomainList
	(*BridgeDomainEntry)(nil),   // 24: tnc.agent.BridgeDomainEntry
	(*VXLANList)(nil),           // 25: tnc.agent.VXLANList
	(*VXLANEntry)(nil),          // 26: tnc.agent.VXLANEntry
	(*UPFApplicationList)(nil),  // 27: tnc.agent.UPFApplicationList
	(*UPFApplication)(nil),      // 28: tnc.agent.UPFApplication
	(*UPFNWIList)(nil),          // 29: tnc.agent.UPFNWIList
	(*UPFNWI)(nil),              // 30: tnc.agent.UPFNWI
	(*UPFPFCPEndpointList)(nil), // 31: tnc.agent.UPFPFCPEndpointList
	(*UPFPFCPEndpoint)(nil),     // 32: tnc.agent.UPFPFCPEndpoint
	(*UPFPolicyList)(nil),       // 33: tnc.agent.UPFPolicyList
	(*UPFPolicy)(nil),           // 34: tnc.agent.UPFPolicy
	(*UPFNATPoolList)(nil),      // 35: tnc.agent.UPFNATPoolList
	(*UPFNATPool)(nil),          // 36: tnc.agent.UPFNATPool
}
var file_proto_agent_proto_depIdxs = []int32{
	6,  // 0: tnc.agent.InterfaceList.interfaces:type_name -> tnc.agent.Interface
	8,  // 1: tnc.agent.NeighborList.neighbors:type_name -> tnc.agent.Neighbor
	10, // 2: tnc.agent.FIBList.entries:type_name -> tnc.agent.FIBEntry
	12, // 3: tnc.agent.ACLList.entries:type_name -> tnc.agent.ACLEntry
	14, // 4: tnc.agent.MemifList.entries:type_name -> tnc.agent.MemifEntry
	16, // 5: tnc.agent.SRv6List.entries:type_name -> tnc.agent.SRv6Entry
	20, // 6: tnc.agent.IPAddressList.entries:type_name -> tnc.agent.IPAddressEntry
	22, // 7: tnc.agent.L2FIBList.entries:type_name -> tnc.agent.L2FIBEntry
	24, // 8: tnc.agent.BridgeDomainList.entries:type_name -> tnc.agent.BridgeDomainEntry
	26, // 9: tnc.agent.VXLANList.entries:type_name -> tnc.agent.VXLANEntry
	28, // 10: tnc.agent.UPFApplicationList.applications:type_name -> tnc.agent.UPFApplication
	30, // 11: tnc.agent.UPFNWIList.nwis:type_name -> tnc.agent.UPFNWI
	32, // 12: tnc.agent.UPFPFCPEndpointList.endpoints:type_name -> tnc.agent.UPFPFCPEndpoint
	34, // 13: tnc.agent.UPFPolicyList.policies:type_name -> tnc.agent.UPFPolicy
	36, // 14: tnc.agent.UPFNATPoolList.pools:type_name -> tnc.agent.UPFNATPool
	0,  // 15: tnc.agent.TncAgent.CollectInterfaces:input_type -> tnc.agent.CollectRequest
	0,  // 16: tnc.agent.TncAgent.CollectNeighbors:input_type -> tnc.agent.CollectRequest
	0,  // 17: tnc.agent.TncAgent.CollectFIB:input_type -> tnc.agent.CollectRequest
	0,  // 18: tnc.agent.TncAgent.CollectACL:input_type -> tnc.agent.CollectRequest
	0,  // 19: tnc.agent.TncAgent.CollectMemif:input_type -> tnc.agent.CollectRequest
	0,  // 20: tnc.agent.TncAgent.CollectSRv6:input_type -> tnc.agent.CollectRequest
	0,  // 21: tnc.agent.TncAgent.CollectVersion:input_type -> tnc.agent.CollectRequest
	0,  // 22: tnc.agent.TncAgent.CollectHardware:input_type -> tnc.agent.CollectRequest
	0,  // 23: tnc.agent.TncAgent.CollectIPAddresses:input_type -> tnc.agent.CollectRequest
	0,  // 24: tnc.agent.TncAgent.CollectL2FIB:input_type -> tnc.agent.CollectRequest
	0,  // 25: tnc.agent.TncAgent.CollectBridgeDomains:input_type -> tnc.agent.CollectRequest
	0,  // 26: tnc.agent.TncAgent.CollectVXLAN:input_type -> tnc.agent.CollectRequest
	0,  // 27: tnc.agent.TncAgent.CollectUPFApplications:input_type -> tnc.agent.CollectRequest
	0,  // 28: tnc.agent.TncAgent.CollectUPFNWI:input_type -> tnc.agent.CollectRequest
	0,  // 29: tnc.agent.TncAgent.CollectUPFPFCPEndpoints:input_type -> tnc.agent.CollectRequest
	0,  // 30: tnc.agent.TncAgent.CollectUPFPolicies:input_type -> tnc.agent.CollectRequest
	0,  // 31: tnc.agent.TncAgent.CollectUPFNATPools:input_type -> tnc.agent.CollectRequest
	2,  // 32: tnc.agent.TncAgent.HealthCheck:input_type -> tnc.agent.HealthCheckRequest
	1,  // 33: tnc.agent.TncAgent.WatchEvents:input_type -> tnc.agent.WatchRequest
	5,  // 34: tnc.agent.TncAgent.CollectInterfaces:output_type -> tnc.agent.InterfaceList
	7,  // 35: tnc.agent.TncAgent.CollectNeighbors:output_type -> tnc.agent.NeighborList
	9,  // 36: tnc.agent.TncAgent.CollectFIB:output_type -> tnc.agent.FIBList
	11, // 37: tnc.agent.TncAgent.CollectACL:output_type -> tnc.agent.ACLList
	13, // 38: tnc.agent.TncAgent.CollectMemif:output_type -> tnc.agent.MemifList
	15, // 39: tnc.agent.TncAgent.CollectSRv6:output_type -> tnc.agent.SRv6List
	17, // 40: tnc.agent.TncAgent.CollectVersion:output_type -> tnc.agent.VersionInfo
	18, // 41: tnc.agent.TncAgent.CollectHardware:output_type -> tnc.agent.HardwareInfo
	19, // 42: tnc.agent.TncAgent.CollectIPAddresses:output_type -> tnc.agent.IPAddressList
	21, // 43: tnc.agent.TncAgent.CollectL2FIB:output_type -> tnc.agent.L2FIBList
	23, // 44: tnc.agent.TncAgent.CollectBridgeDomains:output_type -> tnc.agent.BridgeDomainList
	25, // 45: tnc.agent.TncAgent.CollectVXLAN:output_type -> tnc.agent.VXLANList
	27, // 46: tnc.agent.TncAgent.CollectUPFApplications:output_type -> tnc.agent.UPFApplicationList
	29, // 47: tnc.agent.TncAgent.CollectUPFNWI:output_type -> tnc.agent.UPFNWIList
	31, // 48: tnc.agent.TncAgent.CollectUPFPFCPEndpoints:output_type -> tnc.agent.UPFPFCPEndpointList
	33, // 49: tnc.agent.TncAgent.CollectUPFPolicies:output_type -> tnc.agent.UPFPolicyList
	35, // 50: tnc.agent.TncAgent.CollectUPFNATPools:output_type -> tnc.agent.UPFNATPoolList
	3,  // 51: tnc.agent.TncAgent.HealthCheck:output_type -> tnc.agent.HealthCheckResponse
	4,  // 52: tnc.agent.TncAgent.WatchEvents:output_type -> tnc.agent.Event
	34, // [34:53] is the sub-list for method output_type
	15, // [15:34] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
