// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TncAgent_CollectInterfaces_FullMethodName       = "/tnc.agent.TncAgent/CollectInterfaces"
	TncAgent_CollectNeighbors_FullMethodName        = "/tnc.agent.TncAgent/CollectNeighbors"
	TncAgent_CollectFIB_FullMethodName              = "/tnc.agent.TncAgent/CollectFIB"
	TncAgent_CollectACL_FullMethodName              = "/tnc.agent.TncAgent/CollectACL"
	TncAgent_CollectMemif_FullMethodName            = "/tnc.agent.TncAgent/CollectMemif"
	TncAgent_CollectSRv6_FullMethodName             = "/tnc.agent.TncAgent/CollectSRv6"
	TncAgent_CollectVersion_FullMethodName          = "/tnc.agent.TncAgent/CollectVersion"
	TncAgent_CollectHardware_FullMethodName         = "/tnc.agent.TncAgent/CollectHardware"
	TncAgent_CollectIPAddresses_FullMethodName      = "/tnc.agent.TncAgent/CollectIPAddresses"
	TncAgent_CollectL2FIB_FullMethodName            = "/tnc.agent.TncAgent/CollectL2FIB"
	TncAgent_CollectBridgeDomains_FullMethodName    = "/tnc.agent.TncAgent/CollectBridgeDomains"
	TncAgent_CollectVXLAN_FullMethodName            = "/tnc.agent.TncAgent/CollectVXLAN"
	TncAgent_CollectUPFApplications_FullMethodName  = "/tnc.agent.TncAgent/CollectUPFApplications"
	TncAgent_CollectUPFNWI_FullMethodName           = "/tnc.agent.TncAgent/CollectUPFNWI"
	TncAgent_CollectUPFPFCPEndpoints_FullMethodName = "/tnc.agent.TncAgent/CollectUPFPFCPEndpoints"
	TncAgent_CollectUPFPolicies_FullMethodName      = "/tnc.agent.TncAgent/CollectUPFPolicies"
	TncAgent_CollectUPFNATPools_FullMethodName      = "/tnc.agent.TncAgent/CollectUPFNATPools"
	TncAgent_CollectBFD_FullMethodName              = "/tnc.agent.TncAgent/CollectBFD"
	TncAgent_HealthCheck_FullMethodName             = "/tnc.agent.TncAgent/HealthCheck"
	TncAgent_WatchEvents_FullMethodName             = "/tnc.agent.TncAgent/WatchEvents"
)

// TncAgentClient is the client API for TncAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TncAgent 서비스 정의
type TncAgentClient interface {
	// 조회 기능 (Unary RPC)
	CollectInterfaces(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*InterfaceList, error)
	CollectNeighbors(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*NeighborList, error)
	CollectFIB(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*FIBList, error)
	CollectACL(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*ACLList, error)
	CollectMemif(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*MemifList, error)
	CollectSRv6(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*SRv6List, error)
	CollectVersion(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*VersionInfo, error)
	CollectHardware(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*HardwareInfo, error)
	CollectIPAddresses(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*IPAddressList, error)
	CollectL2FIB(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*L2FIBList, error)
	CollectBridgeDomains(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*BridgeDomainList, error)
	CollectVXLAN(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*VXLANList, error)
	CollectUPFApplications(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*UPFApplicationList, error)
	CollectUPFNWI(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*UPFNWIList, error)
	CollectUPFPFCPEndpoints(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*UPFPFCPEndpointList, error)
	CollectUPFPolicies(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*UPFPolicyList, error)
	CollectUPFNATPools(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*UPFNATPoolList, error)
	CollectBFD(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*BFDList, error)
	// 헬스 체크
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// 이벤트 스트리밍 (Server Streaming)
	WatchEvents(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
}

type tncAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewTncAgentClient(cc grpc.ClientConnInterface) TncAgentClient {
	return &tncAgentClient{cc}
}

func (c *tncAgentClient) CollectInterfaces(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*InterfaceList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InterfaceList)
	err := c.cc.Invoke(ctx, TncAgent_CollectInterfaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tncAgentClient) CollectNeighbors(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*NeighborList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NeighborList)
	err := c.cc.Invoke(ctx, TncAgent_CollectNeighbors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tncAgentClient) CollectFIB(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*FIBList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FIBList)
	err := c.cc.Invoke(ctx, TncAgent_CollectFIB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tncAgentClient) CollectACL(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*ACLList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ACLList)
	err := c.cc.Invoke(ctx, TncAgent_CollectACL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tncAgentClient) CollectMemif(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*MemifList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemifList)
	err := c.cc.Invoke(ctx, TncAgent_CollectMemif_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tncAgentClient) CollectSRv6(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*SRv6List, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SRv6List)
	err := c.cc.Invoke(ctx, TncAgent_CollectSRv6_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tncAgentClient) CollectVersion(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*VersionInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionInfo)
	err := c.cc.Invoke(ctx, TncAgent_CollectVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tncAgentClient) CollectHardware(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*HardwareInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HardwareInfo)
	err := c.cc.Invoke(ctx, TncAgent_CollectHardware_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tncAgentClient) CollectIPAddresses(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*IPAddressList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IPAddressList)
	err := c.cc.Invoke(ctx, TncAgent_CollectIPAddresses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tncAgentClient) CollectL2FIB(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*L2FIBList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(L2FIBList)
	err := c.cc.Invoke(ctx, TncAgent_CollectL2FIB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tncAgentClient) CollectBridgeDomains(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*BridgeDomainList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BridgeDomainList)
	err := c.cc.Invoke(ctx, TncAgent_CollectBridgeDomains_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tncAgentClient) CollectVXLAN(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*VXLANList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VXLANList)
	err := c.cc.Invoke(ctx, TncAgent_CollectVXLAN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tncAgentClient) CollectUPFApplications(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*UPFApplicationList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UPFApplicationList)
	err := c.cc.Invoke(ctx, TncAgent_CollectUPFApplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tncAgentClient) CollectUPFNWI(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*UPFNWIList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UPFNWIList)
	err := c.cc.Invoke(ctx, TncAgent_CollectUPFNWI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tncAgentClient) CollectUPFPFCPEndpoints(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*UPFPFCPEndpointList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UPFPFCPEndpointList)
	err := c.cc.Invoke(ctx, TncAgent_CollectUPFPFCPEndpoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tncAgentClient) CollectUPFPolicies(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*UPFPolicyList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UPFPolicyList)
	err := c.cc.Invoke(ctx, TncAgent_CollectUPFPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tncAgentClient) CollectUPFNATPools(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*UPFNATPoolList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UPFNATPoolList)
	err := c.cc.Invoke(ctx, TncAgent_CollectUPFNATPools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tncAgentClient) CollectBFD(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*BFDList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BFDList)
	err := c.cc.Invoke(ctx, TncAgent_CollectBFD_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tncAgentClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, TncAgent_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tncAgentClient) WatchEvents(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TncAgent_ServiceDesc.Streams[0], TncAgent_WatchEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TncAgent_WatchEventsClient = grpc.ServerStreamingClient[Event]

// TncAgentServer is the server API for TncAgent service.
// All implementations must embed UnimplementedTncAgentServer
// for forward compatibility.
//
// TncAgent 서비스 정의
type TncAgentServer interface {
	// 조회 기능 (Unary RPC)
	CollectInterfaces(context.Context, *CollectRequest) (*InterfaceList, error)
	CollectNeighbors(context.Context, *CollectRequest) (*NeighborList, error)
	CollectFIB(context.Context, *CollectRequest) (*FIBList, error)
	CollectACL(context.Context, *CollectRequest) (*ACLList, error)
	CollectMemif(context.Context, *CollectRequest) (*MemifList, error)
	CollectSRv6(context.Context, *CollectRequest) (*SRv6List, error)
	CollectVersion(context.Context, *CollectRequest) (*VersionInfo, error)
	CollectHardware(context.Context, *CollectRequest) (*HardwareInfo, error)
	CollectIPAddresses(context.Context, *CollectRequest) (*IPAddressList, error)
	CollectL2FIB(context.Context, *CollectRequest) (*L2FIBList, error)
	CollectBridgeDomains(context.Context, *CollectRequest) (*BridgeDomainList, error)
	CollectVXLAN(context.Context, *CollectRequest) (*VXLANList, error)
	CollectUPFApplications(context.Context, *CollectRequest) (*UPFApplicationList, error)
	CollectUPFNWI(context.Context, *CollectRequest) (*UPFNWIList, error)
	CollectUPFPFCPEndpoints(context.Context, *CollectRequest) (*UPFPFCPEndpointList, error)
	CollectUPFPolicies(context.Context, *CollectRequest) (*UPFPolicyList, error)
	CollectUPFNATPools(context.Context, *CollectRequest) (*UPFNATPoolList, error)
	CollectBFD(context.Context, *CollectRequest) (*BFDList, error)
	// 헬스 체크
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// 이벤트 스트리밍 (Server Streaming)
	WatchEvents(*WatchRequest, grpc.ServerStreamingServer[Event]) error
	mustEmbedUnimplementedTncAgentServer()
}

// UnimplementedTncAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTncAgentServer struct{}

func (UnimplementedTncAgentServer) CollectInterfaces(context.Context, *CollectRequest) (*InterfaceList, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectInterfaces not implemented")
}
func (UnimplementedTncAgentServer) CollectNeighbors(context.Context, *CollectRequest) (*NeighborList, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectNeighbors not implemented")
}
func (UnimplementedTncAgentServer) CollectFIB(context.Context, *CollectRequest) (*FIBList, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectFIB not implemented")
}
func (UnimplementedTncAgentServer) CollectACL(context.Context, *CollectRequest) (*ACLList, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectACL not implemented")
}
func (UnimplementedTncAgentServer) CollectMemif(context.Context, *CollectRequest) (*MemifList, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectMemif not implemented")
}
func (UnimplementedTncAgentServer) CollectSRv6(context.Context, *CollectRequest) (*SRv6List, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectSRv6 not implemented")
}
func (UnimplementedTncAgentServer) CollectVersion(context.Context, *CollectRequest) (*VersionInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectVersion not implemented")
}
func (UnimplementedTncAgentServer) CollectHardware(context.Context, *CollectRequest) (*HardwareInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectHardware not implemented")
}
func (UnimplementedTncAgentServer) CollectIPAddresses(context.Context, *CollectRequest) (*IPAddressList, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectIPAddresses not implemented")
}
func (UnimplementedTncAgentServer) CollectL2FIB(context.Context, *CollectRequest) (*L2FIBList, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectL2FIB not implemented")
}
func (UnimplementedTncAgentServer) CollectBridgeDomains(context.Context, *CollectRequest) (*BridgeDomainList, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectBridgeDomains not implemented")
}
func (UnimplementedTncAgentServer) CollectVXLAN(context.Context, *CollectRequest) (*VXLANList, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectVXLAN not implemented")
}
func (UnimplementedTncAgentServer) CollectUPFApplications(context.Context, *CollectRequest) (*UPFApplicationList, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectUPFApplications not implemented")
}
func (UnimplementedTncAgentServer) CollectUPFNWI(context.Context, *CollectRequest) (*UPFNWIList, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectUPFNWI not implemented")
}
func (UnimplementedTncAgentServer) CollectUPFPFCPEndpoints(context.Context, *CollectRequest) (*UPFPFCPEndpointList, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectUPFPFCPEndpoints not implemented")
}
func (UnimplementedTncAgentServer) CollectUPFPolicies(context.Context, *CollectRequest) (*UPFPolicyList, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectUPFPolicies not implemented")
}
func (UnimplementedTncAgentServer) CollectUPFNATPools(context.Context, *CollectRequest) (*UPFNATPoolList, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectUPFNATPools not implemented")
}
func (UnimplementedTncAgentServer) CollectBFD(context.Context, *CollectRequest) (*BFDList, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectBFD not implemented")
}
func (UnimplementedTncAgentServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedTncAgentServer) WatchEvents(*WatchRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method WatchEvents not implemented")
}
func (UnimplementedTncAgentServer) mustEmbedUnimplementedTncAgentServer() {}
func (UnimplementedTncAgentServer) testEmbeddedByValue()                  {}

// UnsafeTncAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TncAgentServer will
// result in compilation errors.
type UnsafeTncAgentServer interface {
	mustEmbedUnimplementedTncAgentServer()
}

func RegisterTncAgentServer(s grpc.ServiceRegistrar, srv TncAgentServer) {
	// If the following call panics, it indicates UnimplementedTncAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TncAgent_ServiceDesc, srv)
}

func _TncAgent_CollectInterfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TncAgentServer).CollectInterfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TncAgent_CollectInterfaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TncAgentServer).CollectInterfaces(ctx, req.(*CollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TncAgent_CollectNeighbors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TncAgentServer).CollectNeighbors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TncAgent_CollectNeighbors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TncAgentServer).CollectNeighbors(ctx, req.(*CollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TncAgent_CollectFIB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TncAgentServer).CollectFIB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TncAgent_CollectFIB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TncAgentServer).CollectFIB(ctx, req.(*CollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TncAgent_CollectACL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TncAgentServer).CollectACL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TncAgent_CollectACL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TncAgentServer).CollectACL(ctx, req.(*CollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TncAgent_CollectMemif_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TncAgentServer).CollectMemif(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TncAgent_CollectMemif_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TncAgentServer).CollectMemif(ctx, req.(*CollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TncAgent_CollectSRv6_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TncAgentServer).CollectSRv6(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TncAgent_CollectSRv6_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TncAgentServer).CollectSRv6(ctx, req.(*CollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TncAgent_CollectVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TncAgentServer).CollectVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TncAgent_CollectVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TncAgentServer).CollectVersion(ctx, req.(*CollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TncAgent_CollectHardware_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TncAgentServer).CollectHardware(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TncAgent_CollectHardware_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TncAgentServer).CollectHardware(ctx, req.(*CollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TncAgent_CollectIPAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TncAgentServer).CollectIPAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TncAgent_CollectIPAddresses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TncAgentServer).CollectIPAddresses(ctx, req.(*CollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TncAgent_CollectL2FIB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TncAgentServer).CollectL2FIB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TncAgent_CollectL2FIB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TncAgentServer).CollectL2FIB(ctx, req.(*CollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TncAgent_CollectBridgeDomains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TncAgentServer).CollectBridgeDomains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TncAgent_CollectBridgeDomains_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TncAgentServer).CollectBridgeDomains(ctx, req.(*CollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TncAgent_CollectVXLAN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TncAgentServer).CollectVXLAN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TncAgent_CollectVXLAN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TncAgentServer).CollectVXLAN(ctx, req.(*CollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TncAgent_CollectUPFApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TncAgentServer).CollectUPFApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TncAgent_CollectUPFApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TncAgentServer).CollectUPFApplications(ctx, req.(*CollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TncAgent_CollectUPFNWI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TncAgentServer).CollectUPFNWI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TncAgent_CollectUPFNWI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TncAgentServer).CollectUPFNWI(ctx, req.(*CollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TncAgent_CollectUPFPFCPEndpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TncAgentServer).CollectUPFPFCPEndpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TncAgent_CollectUPFPFCPEndpoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TncAgentServer).CollectUPFPFCPEndpoints(ctx, req.(*CollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TncAgent_CollectUPFPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TncAgentServer).CollectUPFPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TncAgent_CollectUPFPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TncAgentServer).CollectUPFPolicies(ctx, req.(*CollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TncAgent_CollectUPFNATPools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TncAgentServer).CollectUPFNATPools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TncAgent_CollectUPFNATPools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TncAgentServer).CollectUPFNATPools(ctx, req.(*CollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TncAgent_CollectBFD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TncAgentServer).CollectBFD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TncAgent_CollectBFD_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TncAgentServer).CollectBFD(ctx, req.(*CollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TncAgent_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TncAgentServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TncAgent_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TncAgentServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TncAgent_WatchEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TncAgentServer).WatchEvents(m, &grpc.GenericServerStream[WatchRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TncAgent_WatchEventsServer = grpc.ServerStreamingServer[Event]

// TncAgent_ServiceDesc is the grpc.ServiceDesc for TncAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TncAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tnc.agent.TncAgent",
	HandlerType: (*TncAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CollectInterfaces",
			Handler:    _TncAgent_CollectInterfaces_Handler,
		},
		{
			MethodName: "CollectNeighbors",
			Handler:    _TncAgent_CollectNeighbors_Handler,
		},
		{
			MethodName: "CollectFIB",
			Handler:    _TncAgent_CollectFIB_Handler,
		},
		{
			MethodName: "CollectACL",
			Handler:    _TncAgent_CollectACL_Handler,
		},
		{
			MethodName: "CollectMemif",
			Handler:    _TncAgent_CollectMemif_Handler,
		},
		{
			MethodName: "CollectSRv6",
			Handler:    _TncAgent_CollectSRv6_Handler,
		},
		{
			MethodName: "CollectVersion",
			Handler:    _TncAgent_CollectVersion_Handler,
		},
		{
			MethodName: "CollectHardware",
			Handler:    _TncAgent_CollectHardware_Handler,
		},
		{
			MethodName: "CollectIPAddresses",
			Handler:    _TncAgent_CollectIPAddresses_Handler,
		},
		{
			MethodName: "CollectL2FIB",
			Handler:    _TncAgent_CollectL2FIB_Handler,
		},
		{
			MethodName: "CollectBridgeDomains",
			Handler:    _TncAgent_CollectBridgeDomains_Handler,
		},
		{
			MethodName: "CollectVXLAN",
			Handler:    _TncAgent_CollectVXLAN_Handler,
		},
		{
			MethodName: "CollectUPFApplications",
			Handler:    _TncAgent_CollectUPFApplications_Handler,
		},
		{
			MethodName: "CollectUPFNWI",
			Handler:    _TncAgent_CollectUPFNWI_Handler,
		},
		{
			MethodName: "CollectUPFPFCPEndpoints",
			Handler:    _TncAgent_CollectUPFPFCPEndpoints_Handler,
		},
		{
			MethodName: "CollectUPFPolicies",
			Handler:    _TncAgent_CollectUPFPolicies_Handler,
		},
		{
			MethodName: "CollectUPFNATPools",
			Handler:    _TncAgent_CollectUPFNATPools_Handler,
		},
		{
			MethodName: "CollectBFD",
			Handler:    _TncAgent_CollectBFD_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _TncAgent_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchEvents",
			Handler:       _TncAgent_WatchEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/agent.proto",
}
