// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/tnc/tnc.proto

package tnc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ✅ Metric Type Enum
type MetricType int32

const (
	MetricType_METRIC_UNKNOWN     MetricType = 0 // 기본값: 정의되지 않음
	MetricType_METRIC_DELAY       MetricType = 1 // 패킷 지연 시간 (ms)
	MetricType_METRIC_BANDWIDTH   MetricType = 2 // 링크 대역폭 (Mbps)
	MetricType_METRIC_JITTER      MetricType = 3 // 지터 (ms)
	MetricType_METRIC_PACKET_LOSS MetricType = 4 // 패킷 손실률 (%)
	MetricType_METRIC_COST        MetricType = 5 // 정책 기반 비용
)

// Enum value maps for MetricType.
var (
	MetricType_name = map[int32]string{
		0: "METRIC_UNKNOWN",
		1: "METRIC_DELAY",
		2: "METRIC_BANDWIDTH",
		3: "METRIC_JITTER",
		4: "METRIC_PACKET_LOSS",
		5: "METRIC_COST",
	}
	MetricType_value = map[string]int32{
		"METRIC_UNKNOWN":     0,
		"METRIC_DELAY":       1,
		"METRIC_BANDWIDTH":   2,
		"METRIC_JITTER":      3,
		"METRIC_PACKET_LOSS": 4,
		"METRIC_COST":        5,
	}
)

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}

func (x MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tnc_tnc_proto_enumTypes[0].Descriptor()
}

func (MetricType) Type() protoreflect.EnumType {
	return &file_proto_tnc_tnc_proto_enumTypes[0]
}

func (x MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricType.Descriptor instead.
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return file_proto_tnc_tnc_proto_rawDescGZIP(), []int{0}
}

// ✅ 최초 SR 토폴로지 요청 (TNC → UTNC)
type InitialSRTopologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TncName       string                 `protobuf:"bytes,1,opt,name=tnc_name,json=tncName,proto3" json:"tnc_name,omitempty"` // 🔹 TNC 식별자 (예: MAC 주소 "00:1A:2B:3C:4D:5E")
	Nodes         []*SRNode              `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Links         []*SRLink              `protobuf:"bytes,3,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitialSRTopologyRequest) Reset() {
	*x = InitialSRTopologyRequest{}
	mi := &file_proto_tnc_tnc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialSRTopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialSRTopologyRequest) ProtoMessage() {}

func (x *InitialSRTopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tnc_tnc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialSRTopologyRequest.ProtoReflect.Descriptor instead.
func (*InitialSRTopologyRequest) Descriptor() ([]byte, []int) {
	return file_proto_tnc_tnc_proto_rawDescGZIP(), []int{0}
}

func (x *InitialSRTopologyRequest) GetTncName() string {
	if x != nil {
		return x.TncName
	}
	return ""
}

func (x *InitialSRTopologyRequest) GetNodes() []*SRNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *InitialSRTopologyRequest) GetLinks() []*SRLink {
	if x != nil {
		return x.Links
	}
	return nil
}

// ✅ SR 토폴로지 업데이트 요청
type UpdateSRTopologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TncId         string                 `protobuf:"bytes,1,opt,name=tnc_id,json=tncId,proto3" json:"tnc_id,omitempty"` // 🔹 UTNC가 발급한 ID (최초 InitialSRTopology 응답에서 받은 값)
	Nodes         []*SRNode              `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Links         []*SRLink              `protobuf:"bytes,3,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSRTopologyRequest) Reset() {
	*x = UpdateSRTopologyRequest{}
	mi := &file_proto_tnc_tnc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSRTopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSRTopologyRequest) ProtoMessage() {}

func (x *UpdateSRTopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tnc_tnc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSRTopologyRequest.ProtoReflect.Descriptor instead.
func (*UpdateSRTopologyRequest) Descriptor() ([]byte, []int) {
	return file_proto_tnc_tnc_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateSRTopologyRequest) GetTncId() string {
	if x != nil {
		return x.TncId
	}
	return ""
}

func (x *UpdateSRTopologyRequest) GetNodes() []*SRNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *UpdateSRTopologyRequest) GetLinks() []*SRLink {
	if x != nil {
		return x.Links
	}
	return nil
}

// ✅ SR 토폴로지 삭제 요청
type DeleteSRTopologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TncId         string                 `protobuf:"bytes,1,opt,name=tnc_id,json=tncId,proto3" json:"tnc_id,omitempty"`       // 🔹 UTNC가 발급한 ID
	NodeIds       []string               `protobuf:"bytes,2,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"` // 삭제할 노드 ID 리스트
	LinkIds       []string               `protobuf:"bytes,3,rep,name=link_ids,json=linkIds,proto3" json:"link_ids,omitempty"` // 삭제할 링크 ID 리스트
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSRTopologyRequest) Reset() {
	*x = DeleteSRTopologyRequest{}
	mi := &file_proto_tnc_tnc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSRTopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSRTopologyRequest) ProtoMessage() {}

func (x *DeleteSRTopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tnc_tnc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSRTopologyRequest.ProtoReflect.Descriptor instead.
func (*DeleteSRTopologyRequest) Descriptor() ([]byte, []int) {
	return file_proto_tnc_tnc_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteSRTopologyRequest) GetTncId() string {
	if x != nil {
		return x.TncId
	}
	return ""
}

func (x *DeleteSRTopologyRequest) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

func (x *DeleteSRTopologyRequest) GetLinkIds() []string {
	if x != nil {
		return x.LinkIds
	}
	return nil
}

// ✅ SR 토폴로지 상태 조회 요청
type GetSRTopologyStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TncId         string                 `protobuf:"bytes,1,opt,name=tnc_id,json=tncId,proto3" json:"tnc_id,omitempty"` // 🔹 UTNC가 부여한 ID (최초 InitialSRTopology 응답에서 받은 값)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSRTopologyStatusRequest) Reset() {
	*x = GetSRTopologyStatusRequest{}
	mi := &file_proto_tnc_tnc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSRTopologyStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSRTopologyStatusRequest) ProtoMessage() {}

func (x *GetSRTopologyStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tnc_tnc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSRTopologyStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSRTopologyStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_tnc_tnc_proto_rawDescGZIP(), []int{3}
}

func (x *GetSRTopologyStatusRequest) GetTncId() string {
	if x != nil {
		return x.TncId
	}
	return ""
}

// ✅ SR 토폴로지 상태 응답
type SRTopologyStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Nodes         []*SRNode              `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Links         []*SRLink              `protobuf:"bytes,3,rep,name=links,proto3" json:"links,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 최근 업데이트 시간
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SRTopologyStatusResponse) Reset() {
	*x = SRTopologyStatusResponse{}
	mi := &file_proto_tnc_tnc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SRTopologyStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRTopologyStatusResponse) ProtoMessage() {}

func (x *SRTopologyStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tnc_tnc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRTopologyStatusResponse.ProtoReflect.Descriptor instead.
func (*SRTopologyStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_tnc_tnc_proto_rawDescGZIP(), []int{4}
}

func (x *SRTopologyStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SRTopologyStatusResponse) GetNodes() []*SRNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *SRTopologyStatusResponse) GetLinks() []*SRLink {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *SRTopologyStatusResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ✅ 장애 발생 보고 요청 (TNC → UTNC)
type SRFailureReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TncId         string                 `protobuf:"bytes,1,opt,name=tnc_id,json=tncId,proto3" json:"tnc_id,omitempty"`                         // 🔹 UTNC가 발급한 ID
	FailureType   string                 `protobuf:"bytes,2,opt,name=failure_type,json=failureType,proto3" json:"failure_type,omitempty"`       // 장애 유형 (예: "NODE_DOWN", "LINK_DOWN")
	AffectedNodes []string               `protobuf:"bytes,3,rep,name=affected_nodes,json=affectedNodes,proto3" json:"affected_nodes,omitempty"` // 장애가 발생한 노드 ID 리스트
	AffectedLinks []string               `protobuf:"bytes,4,rep,name=affected_links,json=affectedLinks,proto3" json:"affected_links,omitempty"` // 장애가 발생한 링크 ID 리스트
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                             // 장애 발생 시간
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`                          // 장애 상세 설명
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SRFailureReport) Reset() {
	*x = SRFailureReport{}
	mi := &file_proto_tnc_tnc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SRFailureReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRFailureReport) ProtoMessage() {}

func (x *SRFailureReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tnc_tnc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRFailureReport.ProtoReflect.Descriptor instead.
func (*SRFailureReport) Descriptor() ([]byte, []int) {
	return file_proto_tnc_tnc_proto_rawDescGZIP(), []int{5}
}

func (x *SRFailureReport) GetTncId() string {
	if x != nil {
		return x.TncId
	}
	return ""
}

func (x *SRFailureReport) GetFailureType() string {
	if x != nil {
		return x.FailureType
	}
	return ""
}

func (x *SRFailureReport) GetAffectedNodes() []string {
	if x != nil {
		return x.AffectedNodes
	}
	return nil
}

func (x *SRFailureReport) GetAffectedLinks() []string {
	if x != nil {
		return x.AffectedLinks
	}
	return nil
}

func (x *SRFailureReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SRFailureReport) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// ✅ UTNC의 응답 메시지 (모든 요청 공통)
type TopologyAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                      // 정상 처리 여부 (true: 성공, false: 실패)
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // 오류 코드 (0: 정상, 1: 데이터 오류, 2: gNB/UPF 누락 등)
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                       // 오류 메시지 또는 상태 설명
	TncId         string                 `protobuf:"bytes,4,opt,name=tnc_id,json=tncId,proto3" json:"tnc_id,omitempty"`              // UTNC가 발급한 ID (최초 InitialSRTopology 요청 시 반환)
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                  // 응답 시간 (Unix timestamp)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyAck) Reset() {
	*x = TopologyAck{}
	mi := &file_proto_tnc_tnc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyAck) ProtoMessage() {}

func (x *TopologyAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tnc_tnc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyAck.ProtoReflect.Descriptor instead.
func (*TopologyAck) Descriptor() ([]byte, []int) {
	return file_proto_tnc_tnc_proto_rawDescGZIP(), []int{6}
}

func (x *TopologyAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TopologyAck) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *TopologyAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TopologyAck) GetTncId() string {
	if x != nil {
		return x.TncId
	}
	return ""
}

func (x *TopologyAck) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ✅ SR 노드 정의
type SRNode struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sid            string                 `protobuf:"bytes,3,opt,name=sid,proto3" json:"sid,omitempty"`
	IpAddress      string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	ConnectedNodes []string               `protobuf:"bytes,5,rep,name=connected_nodes,json=connectedNodes,proto3" json:"connected_nodes,omitempty"`
	EndNode        bool                   `protobuf:"varint,6,opt,name=end_node,json=endNode,proto3" json:"end_node,omitempty"` // ✅ 엔드 노드 여부 추가
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SRNode) Reset() {
	*x = SRNode{}
	mi := &file_proto_tnc_tnc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SRNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRNode) ProtoMessage() {}

func (x *SRNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tnc_tnc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRNode.ProtoReflect.Descriptor instead.
func (*SRNode) Descriptor() ([]byte, []int) {
	return file_proto_tnc_tnc_proto_rawDescGZIP(), []int{7}
}

func (x *SRNode) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SRNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SRNode) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *SRNode) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *SRNode) GetConnectedNodes() []string {
	if x != nil {
		return x.ConnectedNodes
	}
	return nil
}

func (x *SRNode) GetEndNode() bool {
	if x != nil {
		return x.EndNode
	}
	return false
}

// ✅ SR 링크 정의
type SRLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkId        string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"` // 🔹 자동 생성된 링크 ID (예: "sr3-sr4")
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Metrics       []*Metric              `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty"`      // 🔹 네트워크 매트릭 리스트
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 🔹 링크 정보의 최신 업데이트 시간 (Unix timestamp)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SRLink) Reset() {
	*x = SRLink{}
	mi := &file_proto_tnc_tnc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SRLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRLink) ProtoMessage() {}

func (x *SRLink) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tnc_tnc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRLink.ProtoReflect.Descriptor instead.
func (*SRLink) Descriptor() ([]byte, []int) {
	return file_proto_tnc_tnc_proto_rawDescGZIP(), []int{8}
}

func (x *SRLink) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *SRLink) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SRLink) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *SRLink) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *SRLink) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ✅ 네트워크 메트릭 정의
type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MetricType             `protobuf:"varint,1,opt,name=type,proto3,enum=tnc.MetricType" json:"type,omitempty"`
	Value         float32                `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"` // 🔹 매트릭 값
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`     // 🔹 단위 (예: "ms", "%", "Mbps")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_proto_tnc_tnc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tnc_tnc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_proto_tnc_tnc_proto_rawDescGZIP(), []int{9}
}

func (x *Metric) GetType() MetricType {
	if x != nil {
		return x.Type
	}
	return MetricType_METRIC_UNKNOWN
}

func (x *Metric) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

var File_proto_tnc_tnc_proto protoreflect.FileDescriptor

const file_proto_tnc_tnc_proto_rawDesc = "" +
	"\n" +
	"\x13proto/tnc/tnc.proto\x12\x03tnc\"{\n" +
	"\x18InitialSRTopologyRequest\x12\x19\n" +
	"\btnc_name\x18\x01 \x01(\tR\atncName\x12!\n" +
	"\x05nodes\x18\x02 \x03(\v2\v.tnc.SRNodeR\x05nodes\x12!\n" +
	"\x05links\x18\x03 \x03(\v2\v.tnc.SRLinkR\x05links\"v\n" +
	"\x17UpdateSRTopologyRequest\x12\x15\n" +
	"\x06tnc_id\x18\x01 \x01(\tR\x05tncId\x12!\n" +
	"\x05nodes\x18\x02 \x03(\v2\v.tnc.SRNodeR\x05nodes\x12!\n" +
	"\x05links\x18\x03 \x03(\v2\v.tnc.SRLinkR\x05links\"f\n" +
	"\x17DeleteSRTopologyRequest\x12\x15\n" +
	"\x06tnc_id\x18\x01 \x01(\tR\x05tncId\x12\x19\n" +
	"\bnode_ids\x18\x02 \x03(\tR\anodeIds\x12\x19\n" +
	"\blink_ids\x18\x03 \x03(\tR\alinkIds\"3\n" +
	"\x1aGetSRTopologyStatusRequest\x12\x15\n" +
	"\x06tnc_id\x18\x01 \x01(\tR\x05tncId\"\x98\x01\n" +
	"\x18SRTopologyStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\x05nodes\x18\x02 \x03(\v2\v.tnc.SRNodeR\x05nodes\x12!\n" +
	"\x05links\x18\x03 \x03(\v2\v.tnc.SRLinkR\x05links\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\xd9\x01\n" +
	"\x0fSRFailureReport\x12\x15\n" +
	"\x06tnc_id\x18\x01 \x01(\tR\x05tncId\x12!\n" +
	"\ffailure_type\x18\x02 \x01(\tR\vfailureType\x12%\n" +
	"\x0eaffected_nodes\x18\x03 \x03(\tR\raffectedNodes\x12%\n" +
	"\x0eaffected_links\x18\x04 \x03(\tR\raffectedLinks\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"\x95\x01\n" +
	"\vTopologyAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x15\n" +
	"\x06tnc_id\x18\x04 \x01(\tR\x05tncId\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\xaa\x01\n" +
	"\x06SRNode\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03sid\x18\x03 \x01(\tR\x03sid\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12'\n" +
	"\x0fconnected_nodes\x18\x05 \x03(\tR\x0econnectedNodes\x12\x19\n" +
	"\bend_node\x18\x06 \x01(\bR\aendNode\"\xa0\x01\n" +
	"\x06SRLink\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12%\n" +
	"\ametrics\x18\x04 \x03(\v2\v.tnc.MetricR\ametrics\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"W\n" +
	"\x06Metric\x12#\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0f.tnc.MetricTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit*\x84\x01\n" +
	"\n" +
	"MetricType\x12\x12\n" +
	"\x0eMETRIC_UNKNOWN\x10\x00\x12\x10\n" +
	"\fMETRIC_DELAY\x10\x01\x12\x14\n" +
	"\x10METRIC_BANDWIDTH\x10\x02\x12\x11\n" +
	"\rMETRIC_JITTER\x10\x03\x12\x16\n" +
	"\x12METRIC_PACKET_LOSS\x10\x04\x12\x0f\n" +
	"\vMETRIC_COST\x10\x052\xec\x02\n" +
	"\n" +
	"TNCService\x12D\n" +
	"\x11InitialSRTopology\x12\x1d.tnc.InitialSRTopologyRequest\x1a\x10.tnc.TopologyAck\x12B\n" +
	"\x10UpdateSRTopology\x12\x1c.tnc.UpdateSRTopologyRequest\x1a\x10.tnc.TopologyAck\x12B\n" +
	"\x10DeleteSRTopology\x12\x1c.tnc.DeleteSRTopologyRequest\x1a\x10.tnc.TopologyAck\x12U\n" +
	"\x13GetSRTopologyStatus\x12\x1f.tnc.GetSRTopologyStatusRequest\x1a\x1d.tnc.SRTopologyStatusResponse\x129\n" +
	"\x0fReportSRFailure\x12\x14.tnc.SRFailureReport\x1a\x10.tnc.TopologyAckB.Z,github.com/clonealpha/esba-tnc-api/proto/tncb\x06proto3"

var (
	file_proto_tnc_tnc_proto_rawDescOnce sync.Once
	file_proto_tnc_tnc_proto_rawDescData []byte
)

func file_proto_tnc_tnc_proto_rawDescGZIP() []byte {
	file_proto_tnc_tnc_proto_rawDescOnce.Do(func() {
		file_proto_tnc_tnc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tnc_tnc_proto_rawDesc), len(file_proto_tnc_tnc_proto_rawDesc)))
	})
	return file_proto_tnc_tnc_proto_rawDescData
}

var file_proto_tnc_tnc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_tnc_tnc_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_tnc_tnc_proto_goTypes = []any{
	(MetricType)(0),                    // 0: tnc.MetricType
	(*InitialSRTopologyRequest)(nil),   // 1: tnc.InitialSRTopologyRequest
	(*UpdateSRTopologyRequest)(nil),    // 2: tnc.UpdateSRTopologyRequest
	(*DeleteSRTopologyRequest)(nil),    // 3: tnc.DeleteSRTopologyRequest
	(*GetSRTopologyStatusRequest)(nil), // 4: tnc.GetSRTopologyStatusRequest
	(*SRTopologyStatusResponse)(nil),   // 5: tnc.SRTopologyStatusResponse
	(*SRFailureReport)(nil),            // 6: tnc.SRFailureReport
	(*TopologyAck)(nil),                // 7: tnc.TopologyAck
	(*SRNode)(nil),                     // 8: tnc.SRNode
	(*SRLink)(nil),                     // 9: tnc.SRLink
	(*Metric)(nil),                     // 10: tnc.Metric
}
var file_proto_tnc_tnc_proto_depIdxs = []int32{
	8,  // 0: tnc.InitialSRTopologyRequest.nodes:type_name -> tnc.SRNode
	9,  // 1: tnc.InitialSRTopologyRequest.links:type_name -> tnc.SRLink
	8,  // 2: tnc.UpdateSRTopologyRequest.nodes:type_name -> tnc.SRNode
	9,  // 3: tnc.UpdateSRTopologyRequest.links:type_name -> tnc.SRLink
	8,  // 4: tnc.SRTopologyStatusResponse.nodes:type_name -> tnc.SRNode
	9,  // 5: tnc.SRTopologyStatusResponse.links:type_name -> tnc.SRLink
	10, // 6: tnc.SRLink.metrics:type_name -> tnc.Metric
	0,  // 7: tnc.Metric.type:type_name -> tnc.MetricType
	1,  // 8: tnc.TNCService.InitialSRTopology:input_type -> tnc.InitialSRTopologyRequest
	2,  // 9: tnc.TNCService.UpdateSRTopology:input_type -> tnc.UpdateSRTopologyRequest
	3,  // 10: tnc.TNCService.DeleteSRTopology:input_type -> tnc.DeleteSRTopologyRequest
	4,  // 11: tnc.TNCService.GetSRTopologyStatus:input_type -> tnc.GetSRTopologyStatusRequest
	6,  // 12: tnc.TNCService.ReportSRFailure:input_type -> tnc.SRFailureReport
	7,  // 13: tnc.TNCService.InitialSRTopology:output_type -> tnc.TopologyAck
	7,  // 14: tnc.TNCService.UpdateSRTopology:output_type -> tnc.TopologyAck
	7,  // 15: tnc.TNCService.DeleteSRTopology:output_type -> tnc.TopologyAck
	5,  // 16: tnc.TNCService.GetSRTopologyStatus:output_type -> tnc.SRTopologyStatusResponse
	7,  // 17: tnc.TNCService.ReportSRFailure:output_type -> tnc.TopologyAck
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_tnc_tnc_proto_init() }
func file_proto_tnc_tnc_proto_init() {
	if File_proto_tnc_tnc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tnc_tnc_proto_rawDesc), len(file_proto_tnc_tnc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tnc_tnc_proto_goTypes,
		DependencyIndexes: file_proto_tnc_tnc_proto_depIdxs,
		EnumInfos:         file_proto_tnc_tnc_proto_enumTypes,
		MessageInfos:      file_proto_tnc_tnc_proto_msgTypes,
	}.Build()
	File_proto_tnc_tnc_proto = out.File
	file_proto_tnc_tnc_proto_goTypes = nil
	file_proto_tnc_tnc_proto_depIdxs = nil
}
