// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/tnc/tnc.proto

package tnc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TNCService_InitialSRTopology_FullMethodName   = "/tnc.TNCService/InitialSRTopology"
	TNCService_UpdateSRTopology_FullMethodName    = "/tnc.TNCService/UpdateSRTopology"
	TNCService_DeleteSRTopology_FullMethodName    = "/tnc.TNCService/DeleteSRTopology"
	TNCService_GetSRTopologyStatus_FullMethodName = "/tnc.TNCService/GetSRTopologyStatus"
	TNCService_ReportSRFailure_FullMethodName     = "/tnc.TNCService/ReportSRFailure"
)

// TNCServiceClient is the client API for TNCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ✅ UTNC가 제공하는 서비스 정의
type TNCServiceClient interface {
	// 🔹 TNC가 UTNC에게 최초 SR 토폴로지 정보를 전달 (UTNC가 tnc_id를 생성하여 응답)
	InitialSRTopology(ctx context.Context, in *InitialSRTopologyRequest, opts ...grpc.CallOption) (*TopologyAck, error)
	// 🔹 SR 토폴로지 정보 업데이트
	UpdateSRTopology(ctx context.Context, in *UpdateSRTopologyRequest, opts ...grpc.CallOption) (*TopologyAck, error)
	// 🔹 특정 SR 토폴로지 정보 삭제
	DeleteSRTopology(ctx context.Context, in *DeleteSRTopologyRequest, opts ...grpc.CallOption) (*TopologyAck, error)
	// 🔹 UTNC가 저장한 최신 SR 토폴로지 상태 조회
	GetSRTopologyStatus(ctx context.Context, in *GetSRTopologyStatusRequest, opts ...grpc.CallOption) (*SRTopologyStatusResponse, error)
	// 🔹 SR 노드 또는 링크 장애 발생 보고
	ReportSRFailure(ctx context.Context, in *SRFailureReport, opts ...grpc.CallOption) (*TopologyAck, error)
}

type tNCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTNCServiceClient(cc grpc.ClientConnInterface) TNCServiceClient {
	return &tNCServiceClient{cc}
}

func (c *tNCServiceClient) InitialSRTopology(ctx context.Context, in *InitialSRTopologyRequest, opts ...grpc.CallOption) (*TopologyAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopologyAck)
	err := c.cc.Invoke(ctx, TNCService_InitialSRTopology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tNCServiceClient) UpdateSRTopology(ctx context.Context, in *UpdateSRTopologyRequest, opts ...grpc.CallOption) (*TopologyAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopologyAck)
	err := c.cc.Invoke(ctx, TNCService_UpdateSRTopology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tNCServiceClient) DeleteSRTopology(ctx context.Context, in *DeleteSRTopologyRequest, opts ...grpc.CallOption) (*TopologyAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopologyAck)
	err := c.cc.Invoke(ctx, TNCService_DeleteSRTopology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tNCServiceClient) GetSRTopologyStatus(ctx context.Context, in *GetSRTopologyStatusRequest, opts ...grpc.CallOption) (*SRTopologyStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SRTopologyStatusResponse)
	err := c.cc.Invoke(ctx, TNCService_GetSRTopologyStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tNCServiceClient) ReportSRFailure(ctx context.Context, in *SRFailureReport, opts ...grpc.CallOption) (*TopologyAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopologyAck)
	err := c.cc.Invoke(ctx, TNCService_ReportSRFailure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TNCServiceServer is the server API for TNCService service.
// All implementations must embed UnimplementedTNCServiceServer
// for forward compatibility.
//
// ✅ UTNC가 제공하는 서비스 정의
type TNCServiceServer interface {
	// 🔹 TNC가 UTNC에게 최초 SR 토폴로지 정보를 전달 (UTNC가 tnc_id를 생성하여 응답)
	InitialSRTopology(context.Context, *InitialSRTopologyRequest) (*TopologyAck, error)
	// 🔹 SR 토폴로지 정보 업데이트
	UpdateSRTopology(context.Context, *UpdateSRTopologyRequest) (*TopologyAck, error)
	// 🔹 특정 SR 토폴로지 정보 삭제
	DeleteSRTopology(context.Context, *DeleteSRTopologyRequest) (*TopologyAck, error)
	// 🔹 UTNC가 저장한 최신 SR 토폴로지 상태 조회
	GetSRTopologyStatus(context.Context, *GetSRTopologyStatusRequest) (*SRTopologyStatusResponse, error)
	// 🔹 SR 노드 또는 링크 장애 발생 보고
	ReportSRFailure(context.Context, *SRFailureReport) (*TopologyAck, error)
	mustEmbedUnimplementedTNCServiceServer()
}

// UnimplementedTNCServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTNCServiceServer struct{}

func (UnimplementedTNCServiceServer) InitialSRTopology(context.Context, *InitialSRTopologyRequest) (*TopologyAck, error) {
	return nil, status.Error(codes.Unimplemented, "method InitialSRTopology not implemented")
}
func (UnimplementedTNCServiceServer) UpdateSRTopology(context.Context, *UpdateSRTopologyRequest) (*TopologyAck, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSRTopology not implemented")
}
func (UnimplementedTNCServiceServer) DeleteSRTopology(context.Context, *DeleteSRTopologyRequest) (*TopologyAck, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSRTopology not implemented")
}
func (UnimplementedTNCServiceServer) GetSRTopologyStatus(context.Context, *GetSRTopologyStatusRequest) (*SRTopologyStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSRTopologyStatus not implemented")
}
func (UnimplementedTNCServiceServer) ReportSRFailure(context.Context, *SRFailureReport) (*TopologyAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportSRFailure not implemented")
}
func (UnimplementedTNCServiceServer) mustEmbedUnimplementedTNCServiceServer() {}
func (UnimplementedTNCServiceServer) testEmbeddedByValue()                    {}

// UnsafeTNCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TNCServiceServer will
// result in compilation errors.
type UnsafeTNCServiceServer interface {
	mustEmbedUnimplementedTNCServiceServer()
}

func RegisterTNCServiceServer(s grpc.ServiceRegistrar, srv TNCServiceServer) {
	// If the following call panics, it indicates UnimplementedTNCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TNCService_ServiceDesc, srv)
}

func _TNCService_InitialSRTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitialSRTopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TNCServiceServer).InitialSRTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TNCService_InitialSRTopology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TNCServiceServer).InitialSRTopology(ctx, req.(*InitialSRTopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TNCService_UpdateSRTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSRTopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TNCServiceServer).UpdateSRTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TNCService_UpdateSRTopology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TNCServiceServer).UpdateSRTopology(ctx, req.(*UpdateSRTopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TNCService_DeleteSRTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSRTopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TNCServiceServer).DeleteSRTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TNCService_DeleteSRTopology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TNCServiceServer).DeleteSRTopology(ctx, req.(*DeleteSRTopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TNCService_GetSRTopologyStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSRTopologyStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TNCServiceServer).GetSRTopologyStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TNCService_GetSRTopologyStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TNCServiceServer).GetSRTopologyStatus(ctx, req.(*GetSRTopologyStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TNCService_ReportSRFailure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SRFailureReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TNCServiceServer).ReportSRFailure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TNCService_ReportSRFailure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TNCServiceServer).ReportSRFailure(ctx, req.(*SRFailureReport))
	}
	return interceptor(ctx, in, info, handler)
}

// TNCService_ServiceDesc is the grpc.ServiceDesc for TNCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TNCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tnc.TNCService",
	HandlerType: (*TNCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitialSRTopology",
			Handler:    _TNCService_InitialSRTopology_Handler,
		},
		{
			MethodName: "UpdateSRTopology",
			Handler:    _TNCService_UpdateSRTopology_Handler,
		},
		{
			MethodName: "DeleteSRTopology",
			Handler:    _TNCService_DeleteSRTopology_Handler,
		},
		{
			MethodName: "GetSRTopologyStatus",
			Handler:    _TNCService_GetSRTopologyStatus_Handler,
		},
		{
			MethodName: "ReportSRFailure",
			Handler:    _TNCService_ReportSRFailure_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tnc/tnc.proto",
}
